"""Extreme stress tests targeting Path B (BacktestNode pipeline) and the full
project surface. 36 tests across 9 groups.

Goes deeper than ``stress_test_portfolios.py``:

* **Path A vs Path B parity** — same config run with ``_USE_BACKTEST_NODE`` off
  and on; metrics compared. Any divergence is a regression.
* **Path B-specific stress** — chunked-per-day data configs (entry window,
  ``run_on_days``, RBO widening), narrow windows, multi-day ranges.
* **Compound risk scenarios** — RBO + trailing SL + move-to-cost + portfolio
  clip + multi-user multipliers all firing at once.
* **Failure-mode probes** — inverted dates, all-disabled slots, empty
  ``run_on_days``, malformed bar types. The engine should fail fast with
  descriptive errors, not silently produce wrong numbers.
* **API stress** — Path B-active backtests via the Flask test client,
  allowlist enforcement, cross-user isolation.

Output: ``5. Logics/extreme_stress_tests/`` per the existing convention.
- ``extreme_stress_results.json`` — raw per-test summaries
- ``extreme_stress_report.html`` — generated by
  ``stress_test_extreme_path_b_report.py``

Run from the project root::

    python stress_test_extreme_path_b.py
    python stress_test_extreme_path_b_report.py
"""

from __future__ import annotations

import copy
import json
import os
import sys
import time
import traceback
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

PROJECT_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(PROJECT_DIR))

from core.backtest_runner import run_portfolio_backtest  # noqa: E402
from core.models import portfolio_from_dict  # noqa: E402
from core.users import save_users, load_users  # noqa: E402

CATALOG_PATH = str(PROJECT_DIR / "catalog")
BASELINE_PATH = PROJECT_DIR / "portfolios" / "_default" / "FX_9_Slot_2015_2024.json"
OUT_DIR = PROJECT_DIR / "5. Logics" / "extreme_stress_tests"
RESULTS_PATH = OUT_DIR / "extreme_stress_results.json"

# Default 5-day window — enough bars for meaningful stress without long runtimes.
DEFAULT_START = "2024-12-02"
DEFAULT_END = "2024-12-06"

# Mid-March covers the Sunday 2024-03-10 DST shift in America/New_York.
DST_START = "2024-03-08"
DST_END = "2024-03-12"

# Multi-month range for Path B chunked-by-day stress.
LONG_START = "2024-10-01"
LONG_END = "2024-12-31"


TEST_REGISTRY = {
    "users": [
        {"user_id": "_default",     "alias": "Default",          "multiplier": 1.0,
         "allowed_instruments": None},
        {"user_id": "alice",        "alias": "Alice (FX)",       "multiplier": 2.0,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "trader_safe",  "alias": "Junior",           "multiplier": 0.01,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "trader_agg",   "alias": "Senior",           "multiplier": 3.0,
         "allowed_instruments": None},
        {"user_id": "runaway",      "alias": "Runaway",          "multiplier": 100000.0,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "alice_only",   "alias": "Alice EURUSD only","multiplier": 1.5,
         "allowed_instruments": ["EURUSD"]},
        {"user_id": "noaccess",     "alias": "Empty allowlist",  "multiplier": 1.0,
         "allowed_instruments": []},
    ]
}


# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────
def _load_baseline_dict(start: str = DEFAULT_START, end: str = DEFAULT_END) -> dict:
    with open(BASELINE_PATH) as f:
        d = json.load(f)
    d["start_date"] = start
    d["end_date"] = end
    for slot in d.get("slots", []):
        slot["start_date"] = start
        slot["end_date"] = end
    return d


def _build_minimal_portfolio(name: str, slots: list[dict], **portfolio_overrides) -> dict:
    pf: dict[str, Any] = {
        "name": name,
        "description": "extreme stress portfolio",
        "starting_capital": 100_000.0,
        "allocation_mode": "equal",
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
        "slots": slots,
    }
    pf.update(portfolio_overrides)
    return pf


def _slot(slot_id: str, bar_type: str, lots: float = 0.01,
          strategy: str = "EMA Cross", **overrides) -> dict:
    s: dict[str, Any] = {
        "slot_id": slot_id,
        "strategy_name": strategy,
        "strategy_params": {},
        "bar_type_str": bar_type,
        "lots": lots,
        "allocation_pct": 0.0,
        "exit_config": {
            "stop_loss_type": "none", "stop_loss_value": 0.0,
            "trailing_sl_step": 0.0, "trailing_sl_offset": 0.0,
            "target_type": "none", "target_value": 0.0,
            "sl_wait_bars": 0, "on_sl_action": "close",
            "on_target_action": "close", "max_re_executions": 0,
            "squareoff_time": None, "squareoff_tz": None,
        },
        "enabled": True,
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
    }
    s.update(overrides)
    return s


def _avg_qty(fills_report) -> float | None:
    if fills_report is None:
        return None
    try:
        if hasattr(fills_report, "empty") and fills_report.empty:
            return None
        for col in ("quantity", "last_qty", "size"):
            if hasattr(fills_report, "columns") and col in fills_report.columns:
                vals = [float(v) for v in fills_report[col] if v is not None]
                return round(sum(vals) / len(vals), 4) if vals else None
    except Exception:
        return None
    return None


def _summarise(results: dict) -> dict:
    per_strategy = results.get("per_strategy", {}) or {}
    return {
        "total_pnl":     round(float(results.get("total_pnl", 0.0) or 0.0), 4),
        "total_trades":  int(results.get("total_trades", 0) or 0),
        "wins":          int(results.get("wins", 0) or 0),
        "losses":        int(results.get("losses", 0) or 0),
        "slot_count":    len(per_strategy),
        "avg_fill_qty":  _avg_qty(results.get("fills_report")),
        "pf_clip_reason": results.get("pf_clip_reason"),
        "path_b":        results.get("path_b"),
    }


def _set_path_b(active: bool) -> None:
    """Toggle the Path B opt-in flag for the next backtest invocation."""
    if active:
        os.environ["_USE_BACKTEST_NODE"] = "1"
    else:
        os.environ["_USE_BACKTEST_NODE"] = "0"


def _full_complex_bundle(d: dict) -> None:
    """Apply RBO + entry window + sqoff + trailing pf_sl + trailing pf_tgt
    + move_sl + reverse-on-SL — the most aggressive setting combination."""
    d["rbo_enabled"] = True
    d["range_monitoring_start"] = "09:00:00"
    d["range_monitoring_end"]   = "10:00:00"
    d["rbo_entry_start"] = "10:00:00"
    d["rbo_entry_end"]   = "15:00:00"
    d["rbo_entry_at"]    = "Any"
    d["rbo_cancel_other_side"] = True
    d["entry_start_time"] = "10:00:00"
    d["entry_end_time"]   = "15:00:00"
    d["squareoff_time"] = "15:30"
    d["squareoff_tz"]   = "UTC"
    d["delay_between_legs_sec"] = 60
    d["pf_sl_enabled"]       = True
    d["pf_sl_value"]         = 80.0
    d["pf_sl_trail_enabled"] = True
    d["pf_sl_trail_every"]   = 20.0
    d["pf_sl_trail_by"]      = 10.0
    d["pf_tgt_enabled"]      = True
    d["pf_tgt_value"]        = 50.0
    d["pf_tgt_trail_enabled"] = True
    d["pf_tgt_trail_when_profit_reach"] = 30.0
    d["pf_tgt_trail_every"]  = 10.0
    d["pf_tgt_trail_by"]     = 5.0
    d["move_sl_enabled"]     = True
    d["move_sl_safety_sec"]  = 300
    d["move_sl_trail_after"] = True


def run_backtest_test(test_id: str, name: str, params: dict,
                      portfolio_dict: dict, expected: str,
                      user_id: str | None,
                      path_b: bool = True,
                      should_error: bool = False,
                      expected_error_substring: str | None = None) -> dict:
    """Generic backtest runner with explicit Path A/B selection."""
    _set_path_b(path_b)
    label = "Path B" if path_b else "Path A"
    print(f"[{test_id}] {label}  {name}  user={user_id}", flush=True)
    t0 = time.time()
    try:
        pf = portfolio_from_dict(portfolio_dict)
        results = run_portfolio_backtest(catalog_path=CATALOG_PATH,
                                         portfolio=pf,
                                         user_id=user_id)
        elapsed = time.time() - t0
        if should_error:
            return {"test_id": test_id, "name": name, "params": params,
                    "expected": expected, "user_id": user_id, "path": label,
                    "status": "fail",
                    "error": f"Expected error but ran successfully: {_summarise(results)}",
                    "elapsed_sec": round(elapsed, 1), "kind": "backtest"}
        summary = _summarise(results)
        summary.update({"test_id": test_id, "name": name, "params": params,
                        "expected": expected, "user_id": user_id, "path": label,
                        "elapsed_sec": round(elapsed, 1), "status": "ok",
                        "kind": "backtest"})
        clip = f"  CLIP={summary['pf_clip_reason']}" if summary.get("pf_clip_reason") else ""
        print(f"   -> ok  pnl=${summary['total_pnl']:.2f}  "
              f"trades={summary['total_trades']}  "
              f"avg_qty={summary['avg_fill_qty']}  "
              f"path_b={summary.get('path_b')}  "
              f"({summary['elapsed_sec']}s){clip}", flush=True)
        return summary
    except Exception as e:
        elapsed = time.time() - t0
        err_str = repr(e)
        if should_error:
            matched = (expected_error_substring is None or
                       expected_error_substring.lower() in err_str.lower())
            verdict = "ok" if matched else "fail"
            print(f"   -> {verdict} (expected error)  err={e!r}  ({elapsed:.1f}s)",
                  flush=True)
            return {"test_id": test_id, "name": name, "params": params,
                    "expected": expected, "user_id": user_id, "path": label,
                    "status": verdict,
                    "expected_error_substring": expected_error_substring,
                    "error": err_str, "elapsed_sec": round(elapsed, 1),
                    "kind": "backtest_negative"}
        tb = traceback.format_exc(limit=5)
        print(f"   -> ERROR  {e!r}  ({elapsed:.1f}s)", flush=True)
        return {"test_id": test_id, "name": name, "params": params,
                "expected": expected, "user_id": user_id, "path": label,
                "status": "error", "error": err_str, "traceback": tb,
                "elapsed_sec": round(elapsed, 1), "kind": "backtest"}


def run_parity_test(test_id: str, name: str, params: dict,
                    portfolio_dict: dict, expected: str,
                    user_id: str | None) -> dict:
    """Run portfolio backtest twice (Path A then Path B) and compare metrics.

    Pass = key numbers match; small floating-point drift on PnL is tolerated
    (within 0.5% relative or $1 absolute). Trade counts must match exactly.
    """
    print(f"[{test_id}] PARITY  {name}  user={user_id}", flush=True)
    t0 = time.time()
    res_a: dict | None = None
    res_b: dict | None = None
    err: str | None = None
    try:
        _set_path_b(False)
        pf_a = portfolio_from_dict(copy.deepcopy(portfolio_dict))
        res_a = _summarise(run_portfolio_backtest(
            catalog_path=CATALOG_PATH, portfolio=pf_a, user_id=user_id))

        _set_path_b(True)
        pf_b = portfolio_from_dict(copy.deepcopy(portfolio_dict))
        res_b = _summarise(run_portfolio_backtest(
            catalog_path=CATALOG_PATH, portfolio=pf_b, user_id=user_id))
    except Exception as e:
        err = repr(e)

    elapsed = time.time() - t0
    if err is not None:
        print(f"   -> ERROR  {err}  ({elapsed:.1f}s)", flush=True)
        return {"test_id": test_id, "name": name, "params": params,
                "expected": expected, "user_id": user_id,
                "status": "error", "error": err,
                "elapsed_sec": round(elapsed, 1), "kind": "parity"}

    # Compare metrics. Trade counts and pf_clip_reason must match exactly.
    # PnL allowed small drift because the path B chunked data configs can
    # introduce slightly different bar sequencing if the catalog has gaps.
    drift_pnl = abs((res_a["total_pnl"] or 0) - (res_b["total_pnl"] or 0))
    pnl_ratio = drift_pnl / max(1.0, abs(res_a["total_pnl"] or 1.0))
    pnl_ok = drift_pnl <= 1.0 or pnl_ratio <= 0.005

    trades_ok = res_a["total_trades"] == res_b["total_trades"]
    clip_ok = res_a["pf_clip_reason"] == res_b["pf_clip_reason"]
    qty_ok = (res_a["avg_fill_qty"] == res_b["avg_fill_qty"]
              or (res_a["avg_fill_qty"] is None and res_b["avg_fill_qty"] is None))

    all_ok = pnl_ok and trades_ok and clip_ok and qty_ok
    verdict = "ok" if all_ok else "fail"
    diffs = []
    if not pnl_ok:
        diffs.append(f"pnl A=${res_a['total_pnl']:.2f} B=${res_b['total_pnl']:.2f} drift={drift_pnl:.2f}")
    if not trades_ok:
        diffs.append(f"trades A={res_a['total_trades']} B={res_b['total_trades']}")
    if not clip_ok:
        diffs.append(f"clip A={res_a['pf_clip_reason']} B={res_b['pf_clip_reason']}")
    if not qty_ok:
        diffs.append(f"qty A={res_a['avg_fill_qty']} B={res_b['avg_fill_qty']}")
    detail = "; ".join(diffs) if diffs else "all metrics match"
    print(f"   -> {verdict}  {detail}  ({elapsed:.1f}s)", flush=True)

    return {"test_id": test_id, "name": name, "params": params,
            "expected": expected, "user_id": user_id,
            "status": verdict, "kind": "parity",
            "path_a": res_a, "path_b": res_b,
            "drift_pnl": round(drift_pnl, 4),
            "drift_pct": round(pnl_ratio * 100, 4),
            "diff_summary": detail,
            "elapsed_sec": round(elapsed, 1)}


def run_api_test(test_id: str, name: str, expected: str, fn) -> dict:
    print(f"[{test_id}] API  {name}", flush=True)
    t0 = time.time()
    try:
        import server
        client = server.app.test_client()
        result = fn(client)
        elapsed = time.time() - t0
        verdict = "ok" if result.get("pass") else "fail"
        print(f"   -> {verdict}: {result.get('detail','')}  ({elapsed:.1f}s)", flush=True)
        return {"test_id": test_id, "name": name, "expected": expected,
                "status": verdict, "detail": result.get("detail", ""),
                "elapsed_sec": round(elapsed, 1), "kind": "api",
                "observations": result.get("observations", {})}
    except Exception as e:
        elapsed = time.time() - t0
        tb = traceback.format_exc(limit=5)
        print(f"   -> ERROR: {e!r}", flush=True)
        return {"test_id": test_id, "name": name, "expected": expected,
                "status": "error", "error": repr(e), "traceback": tb,
                "elapsed_sec": round(elapsed, 1), "kind": "api"}


# ─────────────────────────────────────────────────────────────────────
# 36 tests across 9 groups
# ─────────────────────────────────────────────────────────────────────
def main() -> None:
    saved_registry = load_users()
    save_users(TEST_REGISTRY)

    out: list[dict] = []

    # ═════════════════════════════════════════════════════════════════
    # Group A — Path A vs Path B parity (5 tests)
    # Same config, two engines; metrics must agree.
    # ═════════════════════════════════════════════════════════════════
    pf = _load_baseline_dict()
    out.append(run_parity_test(
        "E01", "Parity: baseline FX_9_Slot, no extras",
        params={"variant": "baseline"},
        portfolio_dict=pf,
        expected="Path A and Path B produce identical PnL/trades/qty/clip",
        user_id="_default",
    ))

    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "09:00:00"
    pf["range_monitoring_end"]   = "10:00:00"
    pf["rbo_entry_start"] = "10:00:00"
    pf["rbo_entry_end"]   = "15:00:00"
    pf["rbo_entry_at"]    = "Any"
    pf["rbo_cancel_other_side"] = True
    out.append(run_parity_test(
        "E02", "Parity: RBO state machine (Any side, cancel_other)",
        params={"rbo_entry_at": "Any", "cancel_other": True},
        portfolio_dict=pf,
        expected="RBO breakouts trigger identically on both paths",
        user_id="_default",
    ))

    pf = _load_baseline_dict()
    pf["pf_sl_enabled"] = True
    pf["pf_sl_value"] = 50.0
    pf["pf_sl_trail_enabled"] = True
    pf["pf_sl_trail_every"] = 15.0
    pf["pf_sl_trail_by"]   = 5.0
    pf["pf_tgt_enabled"] = True
    pf["pf_tgt_value"] = 30.0
    pf["pf_tgt_trail_enabled"] = True
    pf["pf_tgt_trail_when_profit_reach"] = 20.0
    pf["pf_tgt_trail_every"] = 10.0
    pf["pf_tgt_trail_by"] = 5.0
    out.append(run_parity_test(
        "E03", "Parity: trailing pf_sl + trailing pf_tgt (post-hoc clip)",
        params={"pf_sl": "50/trail 15→5", "pf_tgt": "30/trail 20→10/5"},
        portfolio_dict=pf,
        expected="Identical pf_clip_reason and clip timestamp on both paths",
        user_id="alice",
    ))

    pf = _load_baseline_dict()
    pf["move_sl_enabled"] = True
    pf["move_sl_safety_sec"] = 180
    pf["move_sl_trail_after"] = True
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "percentage"
        slot["exit_config"]["stop_loss_value"] = 0.1
        slot["exit_config"]["trailing_sl_step"] = 0.05
        slot["exit_config"]["trailing_sl_offset"] = 0.02
    out.append(run_parity_test(
        "E04", "Parity: move-SL-to-cost + trail_after + per-slot trailing SL",
        params={"move_sl": "180s + trail_after", "slot_sl": "0.1% trailing 0.05/0.02"},
        portfolio_dict=pf,
        expected="Move-to-cost arms identically; trailing ratchet matches",
        user_id="trader_agg",
    ))

    pf = _build_minimal_portfolio(
        "Parity_RBO_multileg",
        slots=[_slot("rb", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
                     strategy="Range Breakout",
                     strategy_params={
                         "num_legs": 3,
                         "leg1_lots": 1, "leg2_lots": 2, "leg3_lots": 3,
                         "range_start_hhmm": 930, "range_end_hhmm": 1030,
                         "breakout_end_hhmm": 1500, "squareoff_hhmm": 1530,
                         "target_pct": 5.0, "stop_pct": 10.0,
                     })])
    out.append(run_parity_test(
        "E05", "Parity: Range Breakout multi-leg (1+2+3 lots, alice ×2.0)",
        params={"strategy": "Range Breakout", "legs": "1+2+3"},
        portfolio_dict=pf,
        expected="Identical leg-quantity ratios and fill timestamps",
        user_id="alice",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group B — Path B-specific stress (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E06: Long range, Path B chunks per-day across 3 months
    pf = _load_baseline_dict(start=LONG_START, end=LONG_END)
    pf["entry_start_time"] = "10:00:00"
    pf["entry_end_time"]   = "15:00:00"
    out.append(run_backtest_test(
        "E06", "Path B: 3-month range with intraday entry window (per-day chunked)",
        params={"range": f"{LONG_START}..{LONG_END}", "entry_window": "10-15 UTC"},
        portfolio_dict=pf,
        expected="path_b='all'; per-day BacktestDataConfig chunking handles range without OOM",
        user_id="alice",
    ))

    # E07: Weekday filter forces per-day data configs
    pf = _load_baseline_dict()
    pf["run_on_days"] = ["Mon", "Wed", "Fri"]
    out.append(run_backtest_test(
        "E07", "Path B: run_on_days=[Mon,Wed,Fri] — gaps in chunked data configs",
        params={"run_on_days": ["Mon", "Wed", "Fri"]},
        portfolio_dict=pf,
        expected="Tue/Thu skipped at chunk-emit time; fills cluster on M/W/F",
        user_id="_default",
    ))

    # E08: Very narrow entry window — Path B should still chunk-by-day
    pf = _load_baseline_dict()
    pf["entry_start_time"] = "12:00:00"
    pf["entry_end_time"]   = "12:05:00"
    out.append(run_backtest_test(
        "E08", "Path B: 5-minute entry window — micro-chunked data configs",
        params={"entry_window": "12:00-12:05"},
        portfolio_dict=pf,
        expected="Few fills, all near 12:00 UTC; engine handles tiny per-day windows",
        user_id="_default",
    ))

    # E09: RBO across multi-day range — daily reset must hold
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "08:00:00"
    pf["range_monitoring_end"]   = "09:00:00"
    pf["rbo_entry_start"] = "09:00:00"
    pf["rbo_entry_end"]   = "16:00:00"
    pf["rbo_range_buffer"] = 15
    pf["rbo_entry_at"] = "RangeHigh"
    out.append(run_backtest_test(
        "E09", "Path B: RBO RangeHigh-only across 5-day range (daily reset)",
        params={"rbo": "RangeHigh, mon=8-9, entry=9-16, buffer=15"},
        portfolio_dict=pf,
        expected="RBO state machine resets each UTC midnight; new range each day",
        user_id="_default",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group C — RBO compound risks (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E10: RBO + cancel_other_side + tight buffer — deferred-DONE behaviour
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "09:00:00"
    pf["range_monitoring_end"]   = "09:30:00"
    pf["rbo_entry_start"] = "09:30:00"
    pf["rbo_entry_end"]   = "11:00:00"
    pf["rbo_range_buffer"] = 1
    pf["rbo_entry_at"] = "Any"
    pf["rbo_cancel_other_side"] = True
    out.append(run_backtest_test(
        "E10", "RBO Any + cancel_other_side + 1-min buffer (deferred-DONE phase)",
        params={"rbo": "Any side, cancel_other, 1min buffer"},
        portfolio_dict=pf,
        expected="Breakout fires once per side; deferred DONE collapses next bar",
        user_id="alice",
    ))

    # E11: RBO + weekday filter excluding monitoring days
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "09:00:00"
    pf["range_monitoring_end"]   = "10:00:00"
    pf["rbo_entry_start"] = "10:00:00"
    pf["rbo_entry_end"]   = "15:00:00"
    pf["run_on_days"] = ["Tue", "Thu"]
    out.append(run_backtest_test(
        "E11", "RBO + run_on_days=[Tue,Thu] — only 2 days have RBO ranges",
        params={"rbo": "on", "run_on_days": ["Tue", "Thu"]},
        portfolio_dict=pf,
        expected="Mon/Wed/Fri filtered before RBO sees them; range built only Tue+Thu",
        user_id="_default",
    ))

    # E12: RBO over multi-day range — confirm daily reset isolates ranges
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "00:00:00"
    pf["range_monitoring_end"]   = "01:00:00"
    pf["rbo_entry_start"] = "01:00:00"
    pf["rbo_entry_end"]   = "23:59:00"
    out.append(run_backtest_test(
        "E12", "RBO with monitoring at UTC midnight — multi-day reset boundary",
        params={"rbo": "monitor 00:00-01:00", "entry": "01:00-23:59"},
        portfolio_dict=pf,
        expected="Each UTC midnight resets phase to IDLE; new range built day 2+",
        user_id="alice",
    ))

    # E13: RBO + slot reverse-on-SL — re-execution must bypass RBO gate
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "09:00:00"
    pf["range_monitoring_end"]   = "10:00:00"
    pf["rbo_entry_start"] = "10:00:00"
    pf["rbo_entry_end"]   = "15:00:00"
    pf["rbo_entry_at"] = "Any"
    pf["rbo_cancel_other_side"] = False
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "percentage"
        slot["exit_config"]["stop_loss_value"] = 0.05
        slot["exit_config"]["on_sl_action"] = "reverse"
        slot["exit_config"]["max_re_executions"] = 5
    out.append(run_backtest_test(
        "E13", "RBO + reverse-on-SL — re-exec bypasses RBO entry gate",
        params={"rbo": "Any/no_cancel", "exit": "reverse + max_re=5"},
        portfolio_dict=pf,
        expected="Initial breakout gated by RBO; subsequent reverses fire freely",
        user_id="alice",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group D — Exit logic compound (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E14: Trailing SL with very tight step → many micro-ratchets
    pf = _load_baseline_dict()
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "trailing"
        slot["exit_config"]["stop_loss_value"] = 0.5
        slot["exit_config"]["trailing_sl_step"] = 0.001  # 0.1 pip per step
        slot["exit_config"]["trailing_sl_offset"] = 0.0005
    out.append(run_backtest_test(
        "E14", "Trailing SL: 0.001 step / 0.0005 offset — micro-ratchets",
        params={"trailing": "step=0.001, offset=0.0005"},
        portfolio_dict=pf,
        expected="SL ratchets dozens of times per profitable trade; never loosens",
        user_id="alice",
    ))

    # E15: Move-SL-to-Cost + trail_after, profitable bias
    pf = _load_baseline_dict()
    pf["move_sl_enabled"] = True
    pf["move_sl_safety_sec"] = 60
    pf["move_sl_trail_after"] = True
    pf["move_sl_no_buy_legs"] = False
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "trailing"
        slot["exit_config"]["stop_loss_value"] = 0.3
        slot["exit_config"]["trailing_sl_step"] = 0.05
        slot["exit_config"]["trailing_sl_offset"] = 0.02
    out.append(run_backtest_test(
        "E15", "Move-to-Cost + trail_after — trailing suppressed until cost hit",
        params={"move_sl": "60s + trail_after", "slot_sl": "trailing 0.3"},
        portfolio_dict=pf,
        expected="trailing ratchet only after move-to-cost fires (per-position one-shot)",
        user_id="trader_agg",
    ))

    # E16: pf_sl trailing across cumulative wins — ratchets multiple times
    pf = _load_baseline_dict()
    pf["pf_sl_enabled"] = True
    pf["pf_sl_value"] = 30.0
    pf["pf_sl_trail_enabled"] = True
    pf["pf_sl_trail_every"] = 5.0   # tight trail-by gate
    pf["pf_sl_trail_by"]    = 2.0
    out.append(run_backtest_test(
        "E16", "Portfolio trailing SL: 5/2 ratchet across many small wins",
        params={"pf_sl": "30 + trail 5/2"},
        portfolio_dict=pf,
        expected="pf_sl ratchets every $5 of cumulative profit; tightens by $2",
        user_id="_default",
    ))

    # E17: pf_tgt trailing with profit-lock minimum
    pf = _load_baseline_dict()
    pf["pf_tgt_enabled"] = True
    pf["pf_tgt_value"] = 100.0
    pf["pf_tgt_trail_enabled"] = True
    pf["pf_tgt_trail_when_profit_reach"] = 20.0
    pf["pf_tgt_trail_lock_min_profit"] = 10.0
    pf["pf_tgt_trail_every"] = 10.0
    pf["pf_tgt_trail_by"]    = 5.0
    out.append(run_backtest_test(
        "E17", "Portfolio TP trailing with profit lock minimum ($10)",
        params={"pf_tgt": "100 + trail when ≥20, lock_min=10, every 10/by 5"},
        portfolio_dict=pf,
        expected="Once profit ≥$20, target floats; can't drop below $10 floor",
        user_id="alice",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group E — Multi-user × Path B (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E18: Runaway × 100k + Path B + cap clamping
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "E18", "Path B: runaway ×100,000 with full bundle — cap MUST clamp",
        params={"user": "runaway", "multiplier": 100000.0,
                "expected_qty": "10,000,000 (FX cap)"},
        portfolio_dict=pf,
        expected="avg_fill_qty clamped to 10M; engine survives all toggles together",
        user_id="runaway",
    ))

    # E19: alice (allowlist) + Path B + RBO + pf_sl trailing
    pf = _load_baseline_dict()
    pf["rbo_enabled"] = True
    pf["range_monitoring_start"] = "09:00:00"
    pf["range_monitoring_end"]   = "10:00:00"
    pf["rbo_entry_start"] = "10:00:00"
    pf["rbo_entry_end"]   = "15:00:00"
    pf["pf_sl_enabled"] = True
    pf["pf_sl_value"] = 60.0
    pf["pf_sl_trail_enabled"] = True
    pf["pf_sl_trail_every"] = 15.0
    pf["pf_sl_trail_by"] = 7.0
    out.append(run_backtest_test(
        "E19", "Path B: alice ×2.0 + RBO + trailing pf_sl",
        params={"user": "alice", "multiplier": 2.0,
                "rbo": "on", "pf_sl": "60 trail 15/7"},
        portfolio_dict=pf,
        expected="qty = 2× baseline across 9 slots; RBO + pf_sl interact correctly",
        user_id="alice",
    ))

    # E20: trader_safe (×0.01) + full bundle + Path B
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "E20", "Path B: trader_safe ×0.01 + full bundle — tiny exposure",
        params={"user": "trader_safe", "multiplier": 0.01},
        portfolio_dict=pf,
        expected="avg_fill_qty == 1% baseline; trailing pf_sl rarely binds (small $$)",
        user_id="trader_safe",
    ))

    # E21: Two users back-to-back, Path A then Path B
    pf = _build_minimal_portfolio(
        "E21_xPath",
        slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
    res_a = run_backtest_test(
        "E21a", "Cross-path stress: alice on Path A",
        params={"user": "alice", "path": "A"},
        portfolio_dict=pf,
        expected="Path A baseline for E21",
        user_id="alice", path_b=False,
    )
    out.append(res_a)
    res_b = run_backtest_test(
        "E21b", "Cross-path stress: alice on Path B (no shared state from E21a)",
        params={"user": "alice", "path": "B"},
        portfolio_dict=pf,
        expected="Path B sees same alice multiplier; no leakage from prior Path A run",
        user_id="alice", path_b=True,
    )
    out.append(res_b)

    # ═════════════════════════════════════════════════════════════════
    # Group F — Time window edge cases (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E22: Squareoff = entry_end_time (race on same bar)
    pf = _load_baseline_dict()
    pf["entry_start_time"] = "10:00:00"
    pf["entry_end_time"]   = "15:00:00"
    pf["squareoff_time"] = "15:00"
    pf["squareoff_tz"]   = "UTC"
    out.append(run_backtest_test(
        "E22", "Squareoff time == entry_end_time (same bar fires both gates)",
        params={"entry_end": "15:00 UTC", "squareoff": "15:00 UTC"},
        portfolio_dict=pf,
        expected="Squareoff wins; no fills past 15:00 UTC; engine handles ordering",
        user_id="_default",
    ))

    # E23: DST transition — squareoff in NY across 2024-03-10
    pf = _load_baseline_dict(start=DST_START, end=DST_END)
    pf["squareoff_time"] = "10:00"
    pf["squareoff_tz"]   = "America/New_York"
    out.append(run_backtest_test(
        "E23", "DST transition (Mar 8-12 2024) with NY squareoff 10:00",
        params={"range": f"{DST_START}..{DST_END}",
                "squareoff": "10:00 America/New_York"},
        portfolio_dict=pf,
        expected="ZoneInfo handles DST shift on 2024-03-10; squareoff hits at right UTC offset",
        user_id="alice",
    ))

    # E24: Weekend-only filter on FX — no market data
    pf = _load_baseline_dict()
    pf["run_on_days"] = ["Sat", "Sun"]
    out.append(run_backtest_test(
        "E24", "run_on_days=[Sat,Sun] on FX (no weekend data) — should error or 0 trades",
        params={"run_on_days": ["Sat", "Sun"]},
        portfolio_dict=pf,
        expected="Path B emits per-day configs for Sat/Sun; catalog returns no bars; total_trades==0",
        user_id="_default",
    ))

    # E25: 1-minute entry window
    pf = _load_baseline_dict()
    pf["entry_start_time"] = "12:30:00"
    pf["entry_end_time"]   = "12:31:00"
    out.append(run_backtest_test(
        "E25", "1-minute entry window 12:30-12:31 UTC (extreme narrow)",
        params={"entry_window": "12:30-12:31"},
        portfolio_dict=pf,
        expected="At most one fill per slot per day (1 bar in window)",
        user_id="alice",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group G — Extreme configurations (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E26: All-knobs-on portfolio (every active setting at extreme value)
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    pf["max_loss"] = 200.0
    pf["max_profit"] = 150.0
    pf["run_on_days"] = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    pf["no_reexec_sl_cost"] = True
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "trailing"
        slot["exit_config"]["stop_loss_value"] = 0.4
        slot["exit_config"]["trailing_sl_step"] = 0.05
        slot["exit_config"]["trailing_sl_offset"] = 0.02
        slot["exit_config"]["target_type"] = "percentage"
        slot["exit_config"]["target_value"] = 0.6
        slot["exit_config"]["on_sl_action"] = "re_execute"
        slot["exit_config"]["max_re_executions"] = 2
    out.append(run_backtest_test(
        "E26", "All-knobs-on: full bundle + max_loss/max_profit + slot trailing + re_execute",
        params={"settings": "every active gate", "user": "trader_agg"},
        portfolio_dict=pf,
        expected="Engine survives every interacting toggle; results sensible",
        user_id="trader_agg",
    ))

    # E27: Tiny slot SL ($0.01 = 1 pip on FX) — fires almost every bar
    pf = _load_baseline_dict()
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "points"
        slot["exit_config"]["stop_loss_value"] = 0.0001  # 1 pip
    out.append(run_backtest_test(
        "E27", "Tiny SL = 0.0001 (1 pip) — should fire on near-every entry",
        params={"slot_sl": "points 0.0001"},
        portfolio_dict=pf,
        expected="Many SL hits, total_trades ≈ entry attempts",
        user_id="_default",
    ))

    # E28: Allocation 200% (deliberate leverage)
    pf = _load_baseline_dict()
    pf["allocation_mode"] = "percentage"
    for slot in pf.get("slots", []):
        slot["allocation_pct"] = 200.0 / max(1, len(pf["slots"]))
    out.append(run_backtest_test(
        "E28", "Allocation_mode=percentage at 200% total (leverage)",
        params={"allocation_mode": "percentage", "sum": 200.0},
        portfolio_dict=pf,
        expected="Engine accepts; capital scales 2× per slot — leverage applied",
        user_id="alice",
    ))

    # E29: 9-strategy mixed portfolio under runaway multiplier
    strategies = ["EMA Cross", "RSI Mean Reversion", "Bollinger Bands"]
    pf_slots = []
    for i, sym in enumerate(["EURUSD", "GBPUSD", "USDJPY"]):
        for j, strat in enumerate(strategies):
            pf_slots.append(_slot(f"e29_{i}_{j}",
                                  f"{sym}.FOREX_MS-1-MINUTE-MID-EXTERNAL",
                                  lots=0.01, strategy=strat))
    pf = _build_minimal_portfolio("E29_runaway_9strat", slots=pf_slots)
    out.append(run_backtest_test(
        "E29", "9 mixed-strategy slots + runaway ×100,000 (Path B + cap clamp)",
        params={"slots": 9, "user": "runaway", "multiplier": 100000.0},
        portfolio_dict=pf,
        expected="All 9 slots clamped to FX cap; engine survives 9× cap-clamped fills",
        user_id="runaway",
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group H — Failure mode probes (4 tests)
    # ═════════════════════════════════════════════════════════════════

    # E30: start_date > end_date (inverted)
    pf = _build_minimal_portfolio(
        "E30_inverted",
        slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)],
        start_date="2024-12-10", end_date="2024-12-02")
    for slot in pf["slots"]:
        slot["start_date"] = "2024-12-10"
        slot["end_date"]   = "2024-12-02"
    out.append(run_backtest_test(
        "E30", "Path B: inverted dates (start > end) — must error or yield 0 trades",
        params={"start": "2024-12-10", "end": "2024-12-02"},
        portfolio_dict=pf,
        expected="Either ValueError 'no data configs' or clean 0-trade return",
        user_id="_default",
        # Either is acceptable; mark non-strict by allowing both error AND ok.
        # We'll inspect the result manually in the report.
    ))

    # E31: run_on_days excludes every weekday in the range
    pf = _load_baseline_dict()
    pf["run_on_days"] = ["Sun"]  # only Sunday — no FX data Sun (only weekdays)
    out.append(run_backtest_test(
        "E31", "run_on_days=[Sun] only (FX has no Sun data) — 0 trades expected",
        params={"run_on_days": ["Sun"]},
        portfolio_dict=pf,
        expected="Path B emits Sun-only configs; catalog returns no bars; 0 trades",
        user_id="_default",
    ))

    # E32: Empty slots list (Path B should fail like Path A)
    pf = _build_minimal_portfolio("E32_empty", slots=[])
    out.append(run_backtest_test(
        "E32", "Path B: 0 slots — must raise 'no enabled slots'",
        params={"slots": 0},
        portfolio_dict=pf,
        expected="ValueError on empty enabled_slots — same behaviour as Path A",
        user_id="_default",
        should_error=True,
        expected_error_substring="no enabled",
    ))

    # E33: Malformed bar_type_str — invalid symbol
    pf = _build_minimal_portfolio(
        "E33_bad_symbol",
        slots=[_slot("bad", "NOTREAL.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
    out.append(run_backtest_test(
        "E33", "Path B: malformed bar_type_str (invalid symbol) — must fail fast",
        params={"bar_type": "NOTREAL.FOREX_MS-1-MINUTE-MID-EXTERNAL"},
        portfolio_dict=pf,
        expected="RuntimeError or KeyError — descriptive failure, not a silent 0-trade",
        user_id="_default",
        should_error=True,
        # Don't pin the exact substring — different layers may raise different
        # messages. Just need an error.
    ))

    # ═════════════════════════════════════════════════════════════════
    # Group I — API + Path B integration (3 tests)
    # ═════════════════════════════════════════════════════════════════

    # E34: Path B-active backtest via /api/portfolios/backtest
    def _e34(client):
        os.environ["_USE_BACKTEST_NODE"] = "1"
        pf = _build_minimal_portfolio(
            "E34_api",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
        r = client.post("/api/portfolios/backtest", json={"portfolio": pf},
                        headers={"X-User-Id": "alice"})
        body = r.get_data(as_text=True)
        return {"pass": (r.status_code == 200 and "complete" in body),
                "detail": f"Path B + alice via API -> {r.status_code}, "
                          f"{len(body.splitlines())} stream lines",
                "observations": {"status": r.status_code,
                                 "lines": len(body.splitlines())}}
    out.append(run_api_test(
        "E34", "Path B + Flask streaming endpoint — /api/portfolios/backtest",
        expected="HTTP 200 with multi-line stream; final 'complete' line present",
        fn=_e34,
    ))

    # E35: Allowlist enforcement at backtest endpoint (Path B)
    def _e35(client):
        os.environ["_USE_BACKTEST_NODE"] = "1"
        pf = _build_minimal_portfolio("E35_block", slots=[
            _slot("eu", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01),
            _slot("bt", "BTCUSD.BINANCE_MS-1-DAY-LAST-EXTERNAL", lots=1.0),
        ])
        r = client.post("/api/portfolios/backtest", json={"portfolio": pf},
                        headers={"X-User-Id": "alice_only"})
        # alice_only allowlist is ["EURUSD"] — BTCUSD must be rejected
        body = r.get_data(as_text=True)
        return {"pass": r.status_code in (400, 403),
                "detail": f"alice_only (allowlist=[EURUSD]) backtest EURUSD+BTCUSD -> {r.status_code}",
                "observations": {"status": r.status_code,
                                 "snippet": body[:200]}}
    out.append(run_api_test(
        "E35", "Backtest endpoint blocks portfolio with out-of-allowlist symbol",
        expected="HTTP 400/403 — second slot (BTCUSD) fails allowlist check",
        fn=_e35,
    ))

    # E36: Path B portfolio CRUD per user
    def _e36(client):
        os.environ["_USE_BACKTEST_NODE"] = "1"
        pf = _build_minimal_portfolio("E36_pathB_crud",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.025)])
        r1 = client.post("/api/portfolios/save", json=pf,
                         headers={"X-User-Id": "alice"})
        r2 = client.get("/api/portfolios/load?name=E36_pathB_crud",
                        headers={"X-User-Id": "alice"})
        loaded = (r2.json or {}).get("portfolio", {})
        loaded_lots = (loaded.get("slots", [{}])[0] or {}).get("lots")
        r3 = client.post("/api/portfolios/backtest", json={"portfolio": pf},
                         headers={"X-User-Id": "alice"})
        body3 = r3.get_data(as_text=True)
        r4 = client.post("/api/portfolios/delete", json={"name": "E36_pathB_crud"},
                         headers={"X-User-Id": "alice"})
        ok = (r1.status_code == 200 and r2.status_code == 200
              and loaded_lots == 0.025 and r3.status_code == 200
              and "complete" in body3 and r4.status_code == 200)
        return {"pass": ok,
                "detail": f"save={r1.status_code} load={r2.status_code}({loaded_lots}) "
                          f"bt={r3.status_code} del={r4.status_code}",
                "observations": {"loaded_name": loaded.get("name"),
                                 "stream_lines": len(body3.splitlines())}}
    out.append(run_api_test(
        "E36", "Path B portfolio CRUD: save → load → backtest → delete (alice)",
        expected="All four endpoints 200; lots round-trip; backtest streams to completion",
        fn=_e36,
    ))

    # ─────────────────────────────────────────────────────────────────
    # Persist + restore
    # ─────────────────────────────────────────────────────────────────
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nWrote {len(out)} test results -> {RESULTS_PATH}", flush=True)

    save_users(saved_registry)
    print(f"Restored original registry "
          f"({len(saved_registry.get('users', []))} users)", flush=True)

    # Reset env so we don't leak Path B state to other test scripts
    os.environ.pop("_USE_BACKTEST_NODE", None)


if __name__ == "__main__":
    main()
