"""Stoploss tab stress tests — 16 tests covering every per-slot SL/TP setting.

Targets the Exit Settings (stoploss) tab inputs surfaced in the slot/leg modal:

* ``stop_loss_type``  ∈ {none, percentage, points, trailing}
* ``stop_loss_value`` (numeric)
* ``trailing_sl_step`` / ``trailing_sl_offset`` (only for type=trailing)
* ``target_type``     ∈ {none, percentage, points}
* ``target_value``
* ``target_lock_trigger`` / ``target_lock_minimum`` (target lock SL ratchet)
* ``sl_wait_bars``    (delay-confirmation before honoring SL)
* ``on_sl_action``    ∈ {close, re_execute, reverse}
* ``on_target_action`` ∈ {close, re_execute, reverse}
* ``max_re_executions``

Each test builds a synthetic portfolio with deliberate parameter combinations,
runs the backtest, then verifies report invariants against the produced
orderbook (EXIT REASON, trade counts, PnL signs, re-entries, etc.).

Output: ``5. Logics/stoploss_tests/`` per the existing convention.
- ``stoploss_results.json``           — raw per-test summaries
- ``stoploss_report.html``            — generated by the companion report script

Run from the project root::

    python stress_test_stoploss.py
    python stress_test_stoploss_report.py
"""

from __future__ import annotations

import json
import os
import sys
import time
import traceback
from collections import Counter
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

PROJECT_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(PROJECT_DIR))

from core.backtest_runner import run_portfolio_backtest  # noqa: E402
from core.models import portfolio_from_dict  # noqa: E402
from core.report_generator import build_orderbook_dataframe  # noqa: E402

CATALOG_PATH = str(PROJECT_DIR / "catalog")
OUT_DIR = PROJECT_DIR / "5. Logics" / "stoploss_tests"
RESULTS_PATH = OUT_DIR / "stoploss_results.json"
PORTFOLIOS_DIR = OUT_DIR / "portfolios"

# 5-day window — enough bars (1-min EURUSD = ~1440/day = ~7000 bars) for
# meaningful SL/TP exercise without long runtimes.
DEFAULT_START = "2024-12-02"
DEFAULT_END = "2024-12-06"

# Use Path A (the in-process BacktestEngine) so we can compare orderbook
# rows row-by-row deterministically. Path B parity is already covered by
# stress_test_extreme_path_b.py.
os.environ["_USE_BACKTEST_NODE"] = "0"


# ─────────────────────────────────────────────────────────────────────
# Portfolio builders
# ─────────────────────────────────────────────────────────────────────
def _slot(slot_id: str,
          bar_type: str = "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL",
          lots: float = 0.01,
          strategy: str = "EMA Cross",
          strategy_params: dict | None = None,
          start: str = DEFAULT_START,
          end: str = DEFAULT_END,
          **exit_overrides) -> dict:
    """Build a slot dict with a default exit_config plus any overrides."""
    ec: dict[str, Any] = {
        "stop_loss_type": "none", "stop_loss_value": 0.0,
        "trailing_sl_step": 0.0, "trailing_sl_offset": 0.0,
        "target_type": "none", "target_value": 0.0,
        "target_lock_trigger": None, "target_lock_minimum": None,
        "sl_wait_bars": 0,
        "on_sl_action": "close", "on_target_action": "close",
        "max_re_executions": 0,
        "squareoff_time": None, "squareoff_tz": None,
    }
    ec.update(exit_overrides)
    return {
        "slot_id": slot_id,
        "strategy_name": strategy,
        "strategy_params": strategy_params or {},
        "bar_type_str": bar_type,
        "lots": lots,
        "allocation_pct": 0.0,
        "exit_config": ec,
        "enabled": True,
        "start_date": start,
        "end_date": end,
    }


def _portfolio(name: str, slots: list[dict], **overrides) -> dict:
    pf: dict[str, Any] = {
        "name": name,
        "description": "stoploss tab stress portfolio",
        "starting_capital": 100_000.0,
        "allocation_mode": "equal",
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
        "slots": slots,
    }
    pf.update(overrides)
    return pf


# ─────────────────────────────────────────────────────────────────────
# Verification helpers
# ─────────────────────────────────────────────────────────────────────
def _exit_reason_counts(orderbook) -> dict[str, int]:
    """Count occurrences of each EXIT REASON value in the orderbook."""
    if orderbook is None or orderbook.empty:
        return {}
    counts: Counter[str] = Counter()
    for v in orderbook["EXIT REASON"].fillna("").astype(str):
        counts[v.strip() or "(blank)"] += 1
    return dict(counts)


def _fills_tag_counts(results: dict) -> dict[str, int]:
    """Count exit-tag prefixes from fills_report (engine source of truth).

    ``fills_report["tags"]`` holds the structured close-reason set by
    ManagedExitStrategy._handle_exit. Tags are stored as ``[reason_str]``
    (a 1-element list) on the closing fill; entry fills carry the
    signal name. Reverse on SL/TP tags appear here even when the
    orderbook builder loses them due to close+open ts-collision —
    counting them here is the engine-level ground truth.
    """
    fills = results.get("fills_report")
    if fills is None or len(fills) == 0:
        return {}
    counts: Counter[str] = Counter()
    for tg in fills["tags"]:
        if isinstance(tg, list) and tg:
            s = str(tg[0])
        elif tg:
            s = str(tg)
        else:
            continue
        # Only count exit reasons (closes). Skip entry signals.
        prefix = s.split(":", 1)[0].strip()
        if prefix in {"Stop Loss", "Trailing SL", "Take Profit",
                      "Reverse on SL", "Reverse on TP"}:
            counts[prefix] += 1
    return dict(counts)


def _summarise(results: dict, user_id: str | None = None,
               portfolio_name: str = "stoploss_test") -> dict:
    """Run report_generator over results and pull verification metrics.

    ``run_portfolio_backtest`` returns merged ``fills_report`` /
    ``positions_report`` at the top level. ``build_orderbook_dataframe``
    expects ``{strategy_name: results_dict}`` so we wrap the merged
    results under the portfolio name (matching how server.py does it).

    Captures both the orderbook EXIT REASON view (what the user sees)
    and the fills_report tag view (engine source of truth) so we can
    distinguish a missing engine-level tag from a report-layer bug.
    """
    orderbook = build_orderbook_dataframe(
        {portfolio_name: results}, user_id=user_id)
    exit_counts = _exit_reason_counts(orderbook)
    fills_tag_counts = _fills_tag_counts(results)
    pnl_total = float(orderbook["PNL"].sum()) if (orderbook is not None and not orderbook.empty) else 0.0
    n_trades = int(len(orderbook)) if orderbook is not None else 0
    n_wins = int((orderbook["PNL"] > 0).sum()) if n_trades else 0
    n_losses = int((orderbook["PNL"] < 0).sum()) if n_trades else 0
    return {
        "orderbook_pnl":   round(pnl_total, 4),
        "orderbook_trades": n_trades,
        "orderbook_wins":  n_wins,
        "orderbook_losses": n_losses,
        "exit_reason_counts": exit_counts,
        "fills_tag_counts":   fills_tag_counts,
        "engine_pnl":      round(float(results.get("total_pnl", 0.0) or 0.0), 4),
        "engine_trades":   int(results.get("total_trades", 0) or 0),
        "engine_wins":     int(results.get("wins", 0) or 0),
        "engine_losses":   int(results.get("losses", 0) or 0),
    }


def _verify(observed: dict, checks: list[tuple[str, bool, str]]) -> dict:
    """Run a list of (label, expr, detail) checks. Returns pass/fail summary."""
    failed = [(label, detail) for label, ok, detail in checks if not ok]
    passed = [(label, detail) for label, ok, detail in checks if ok]
    return {
        "verification_pass":  len(failed) == 0,
        "checks_passed":      [{"label": l, "detail": d} for l, d in passed],
        "checks_failed":      [{"label": l, "detail": d} for l, d in failed],
        "verification_count": f"{len(passed)}/{len(passed) + len(failed)}",
    }


# ─────────────────────────────────────────────────────────────────────
# Test runner
# ─────────────────────────────────────────────────────────────────────
def run_test(test_id: str, name: str, params: dict, portfolio_dict: dict,
             expected: str, verifier=None, user_id: str | None = None) -> dict:
    print(f"[{test_id}] {name}", flush=True)
    t0 = time.time()
    PORTFOLIOS_DIR.mkdir(parents=True, exist_ok=True)
    saved_pf_path = PORTFOLIOS_DIR / f"{test_id}_{portfolio_dict['name']}.json"
    saved_pf_path.write_text(json.dumps(portfolio_dict, indent=2, default=str),
                             encoding="utf-8")
    try:
        pf = portfolio_from_dict(portfolio_dict)
        results = run_portfolio_backtest(catalog_path=CATALOG_PATH,
                                         portfolio=pf,
                                         user_id=user_id)
        elapsed = time.time() - t0
        summary = _summarise(results, user_id=user_id,
                             portfolio_name=portfolio_dict["name"])

        verification: dict[str, Any] = {"verification_pass": True,
                                        "verification_count": "n/a",
                                        "checks_passed": [],
                                        "checks_failed": []}
        if verifier is not None:
            try:
                checks = verifier(summary)
                verification = _verify(summary, checks)
            except Exception as ve:
                verification = {
                    "verification_pass": False,
                    "verification_count": "verifier_error",
                    "checks_passed": [],
                    "checks_failed": [{
                        "label": "verifier_exception",
                        "detail": repr(ve),
                    }],
                }

        status = "ok" if verification["verification_pass"] else "fail"
        out = {
            "test_id": test_id, "name": name, "params": params,
            "expected": expected, "user_id": user_id,
            "portfolio_path": str(saved_pf_path.relative_to(PROJECT_DIR)),
            "elapsed_sec": round(elapsed, 1),
            "status": status,
            **summary, **verification,
        }
        print(f"   -> {status.upper()}  trades={summary['orderbook_trades']}  "
              f"pnl=${summary['orderbook_pnl']:.2f}  "
              f"verify={verification['verification_count']}  ({elapsed:.1f}s)",
              flush=True)
        return out
    except Exception as e:
        elapsed = time.time() - t0
        tb = traceback.format_exc(limit=5)
        print(f"   -> ERROR  {e!r}  ({elapsed:.1f}s)", flush=True)
        return {
            "test_id": test_id, "name": name, "params": params,
            "expected": expected, "user_id": user_id,
            "portfolio_path": str(saved_pf_path.relative_to(PROJECT_DIR)),
            "elapsed_sec": round(elapsed, 1), "status": "error",
            "error": repr(e), "traceback": tb,
        }


# ─────────────────────────────────────────────────────────────────────
# 16 tests
# ─────────────────────────────────────────────────────────────────────
def main() -> None:
    out: list[dict] = []

    # ═══════════════════════════════════════════════════════════════════
    # S01 — Baseline: no SL, no TP (sanity)
    # All exit_config defaults. Trades close only on opposite signal /
    # squareoff. EXIT REASON should never contain Stop Loss / Take Profit.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S01_baseline", slots=[
        _slot("a", strategy="EMA Cross",
              strategy_params={"fast_period": 5, "slow_period": 20})])

    def _v_s01(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0,
             f"got {s['orderbook_trades']} trades"),
            ("no_stop_loss_exits", "Stop Loss" not in ec,
             f"exit reasons: {sorted(ec.keys())}"),
            ("no_trailing_sl_exits", "Trailing SL" not in ec,
             f"trailing should not appear without configured SL"),
            ("no_take_profit_exits", "Take Profit" not in ec,
             f"target_type=none → no Take Profit exits"),
        ]

    out.append(run_test("S01", "Baseline: no SL/TP — strategy-signal exits only",
        params={"stop_loss_type": "none", "target_type": "none"},
        portfolio_dict=pf,
        expected="No 'Stop Loss' / 'Trailing SL' / 'Take Profit' in EXIT REASON; "
                 "trades close on opposite signal.",
        verifier=_v_s01))

    # ═══════════════════════════════════════════════════════════════════
    # S02 — Percentage SL: 0.10% on EURUSD
    # 0.1% on EURUSD ≈ 10 pips. Should produce a healthy mix of SL exits.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S02_percentage_sl", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.1)])

    def _v_s02(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_stop_loss_exits", "Stop Loss" in ec,
             f"expected 'Stop Loss' in exit reasons {sorted(ec.keys())}"),
            ("no_trailing_sl_exits", "Trailing SL" not in ec,
             f"fixed SL must not be tagged as 'Trailing SL'"),
            ("losers_present", s["orderbook_losses"] > 0,
             f"SL hits should produce losing trades; got {s['orderbook_losses']}"),
        ]

    out.append(run_test("S02", "Percentage SL = 0.10% (10 pips on EURUSD)",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.1},
        portfolio_dict=pf,
        expected="EXIT REASON contains 'Stop Loss' rows; some losing trades.",
        verifier=_v_s02))

    # ═══════════════════════════════════════════════════════════════════
    # S03 — Points SL: 0.0010 (= 10 pips on EURUSD price)
    # Equivalent magnitude to S02 but priced in absolute points instead
    # of percent. Same behaviour expected: Stop Loss exits + losses.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S03_points_sl", slots=[
        _slot("a", stop_loss_type="points", stop_loss_value=0.0010)])

    def _v_s03(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_stop_loss_exits", "Stop Loss" in ec,
             f"expected 'Stop Loss' in {sorted(ec.keys())}"),
            ("losers_present", s["orderbook_losses"] > 0,
             f"got {s['orderbook_losses']} losers"),
        ]

    out.append(run_test("S03", "Points SL = 0.0010 (10 pips absolute on EURUSD)",
        params={"stop_loss_type": "points", "stop_loss_value": 0.0010},
        portfolio_dict=pf,
        expected="Same behaviour as percentage SL but priced in absolute points.",
        verifier=_v_s03))

    # ═══════════════════════════════════════════════════════════════════
    # S04 — Trailing SL: step 0.05% / offset 0.02%
    # Initial SL set by stop_loss_value (0.30%); ratchets in 0.05%
    # profit increments tightening by 0.02% each step. Exits should be
    # tagged 'Trailing SL' once the watermark moves the SL.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S04_trailing_sl", slots=[
        _slot("a", stop_loss_type="trailing", stop_loss_value=0.30,
              trailing_sl_step=0.05, trailing_sl_offset=0.02)])

    def _v_s04(s):
        ec = s["exit_reason_counts"]
        sl_count = ec.get("Stop Loss", 0) + ec.get("Trailing SL", 0)
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_sl_exits", sl_count > 0,
             f"need at least one SL/Trailing SL exit; counts={ec}"),
            ("trailing_or_fixed_sl_appears",
             "Trailing SL" in ec or "Stop Loss" in ec,
             f"either label acceptable; got {sorted(ec.keys())}"),
        ]

    out.append(run_test("S04", "Trailing SL: initial 0.30%, step 0.05% / offset 0.02%",
        params={"stop_loss_type": "trailing", "stop_loss_value": 0.30,
                "trailing_sl_step": 0.05, "trailing_sl_offset": 0.02},
        portfolio_dict=pf,
        expected="Mix of 'Trailing SL' and 'Stop Loss' exits; trailing hits "
                 "after watermark advances.",
        verifier=_v_s04))

    # ═══════════════════════════════════════════════════════════════════
    # S05 — Tight micro-ratchet trailing SL
    # Ultra-tight step+offset (0.005% / 0.002%). Profitable trades should
    # trail SL many times before exit. Should produce many 'Trailing SL' tags.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S05_micro_trailing", slots=[
        _slot("a", stop_loss_type="trailing", stop_loss_value=0.20,
              trailing_sl_step=0.005, trailing_sl_offset=0.002)])

    def _v_s05(s):
        ec = s["exit_reason_counts"]
        sl_count = ec.get("Stop Loss", 0) + ec.get("Trailing SL", 0)
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_sl_exits", sl_count > 0,
             f"micro-trailing must hit SL; counts={ec}"),
        ]

    out.append(run_test("S05", "Trailing SL micro: step 0.005% / offset 0.002%",
        params={"stop_loss_type": "trailing", "stop_loss_value": 0.20,
                "trailing_sl_step": 0.005, "trailing_sl_offset": 0.002},
        portfolio_dict=pf,
        expected="Many trailing-SL ratchets per profitable trade; "
                 "Trailing SL exits dominate.",
        verifier=_v_s05))

    # ═══════════════════════════════════════════════════════════════════
    # S06 — Trailing SL + target_lock
    # target_lock_trigger=0.10% raises SL to target_lock_minimum=0.05%.
    # SL hits AFTER lock should be tagged 'Trailing SL' (target_lock
    # routes through the SL exit path with _was_trailed=True).
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S06_target_lock", slots=[
        _slot("a", stop_loss_type="trailing", stop_loss_value=0.30,
              trailing_sl_step=0.10, trailing_sl_offset=0.05,
              target_lock_trigger=0.10, target_lock_minimum=0.05)])

    def _v_s06(s):
        ec = s["exit_reason_counts"]
        sl_count = ec.get("Stop Loss", 0) + ec.get("Trailing SL", 0)
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_sl_exits", sl_count > 0,
             f"target_lock-armed trades must hit some SL; counts={ec}"),
        ]

    out.append(run_test("S06", "Target lock: trigger=0.10%, minimum=0.05% + trailing 0.30%",
        params={"target_lock_trigger": 0.10, "target_lock_minimum": 0.05,
                "stop_loss_type": "trailing", "trailing_sl_step": 0.10,
                "trailing_sl_offset": 0.05},
        portfolio_dict=pf,
        expected="Once profit ≥ 0.10%, SL ratchets to 0.05% (locked-in profit). "
                 "Subsequent SL hits tagged Trailing SL.",
        verifier=_v_s06))

    # ═══════════════════════════════════════════════════════════════════
    # S07 — Percentage SL + Percentage TP (both fixed)
    # 0.20% SL / 0.30% TP. Trades exit at SL or TP whichever hits first.
    # Should see both 'Stop Loss' and 'Take Profit' rows.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S07_pct_sl_pct_tp", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.20,
              target_type="percentage", target_value=0.30)])

    def _v_s07(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_stop_loss", "Stop Loss" in ec,
             f"need Stop Loss; got {sorted(ec.keys())}"),
            ("has_take_profit", "Take Profit" in ec,
             f"need Take Profit; got {sorted(ec.keys())}"),
            ("winners_present", s["orderbook_wins"] > 0,
             f"TP hits should give wins; got {s['orderbook_wins']}"),
            ("losers_present", s["orderbook_losses"] > 0,
             f"SL hits should give losses; got {s['orderbook_losses']}"),
        ]

    out.append(run_test("S07", "Percentage SL=0.20% + Percentage TP=0.30%",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.20,
                "target_type": "percentage", "target_value": 0.30},
        portfolio_dict=pf,
        expected="Both 'Stop Loss' and 'Take Profit' exits in orderbook; "
                 "wins from TP, losses from SL.",
        verifier=_v_s07))

    # ═══════════════════════════════════════════════════════════════════
    # S08 — Points SL + Points TP
    # 0.0015 SL / 0.0030 TP — same magnitude as S07 in absolute points.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S08_pts_sl_pts_tp", slots=[
        _slot("a", stop_loss_type="points", stop_loss_value=0.0015,
              target_type="points", target_value=0.0030)])

    def _v_s08(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_stop_loss_or_tp", "Stop Loss" in ec or "Take Profit" in ec,
             f"need at least SL or TP exits; got {sorted(ec.keys())}"),
        ]

    out.append(run_test("S08", "Points SL=0.0015 + Points TP=0.0030",
        params={"stop_loss_type": "points", "stop_loss_value": 0.0015,
                "target_type": "points", "target_value": 0.0030},
        portfolio_dict=pf,
        expected="SL and TP exits priced in absolute points (1.5/3.0 pips).",
        verifier=_v_s08))

    # ═══════════════════════════════════════════════════════════════════
    # S09 — on_sl_action="reverse"
    # When SL fires, flip side instead of just closing. EXIT REASON should
    # contain 'Reverse on SL'. The reversed entry then has its OWN SL/TP.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S09_reverse_on_sl", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.10,
              on_sl_action="reverse",
              # Reverse needs a TP exit OR another SL hit to close out:
              target_type="percentage", target_value=0.20)])

    def _v_s09(s):
        ec = s["exit_reason_counts"]
        ft = s["fills_tag_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("engine_emits_reverse_on_sl", ft.get("Reverse on SL", 0) > 0,
             f"fills_report.tags must contain 'Reverse on SL'; got {ft}"),
            ("orderbook_propagates_reverse_on_sl", "Reverse on SL" in ec,
             f"orderbook EXIT REASON should also contain 'Reverse on SL'; "
             f"got {sorted(ec.keys())} — close+open same-ts collision in "
             f"_build_fills_lookup masks the close tag"),
        ]

    out.append(run_test("S09", "on_sl_action='reverse' — SL flips position",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.10,
                "on_sl_action": "reverse",
                "target_type": "percentage", "target_value": 0.20},
        portfolio_dict=pf,
        expected="EXIT REASON includes 'Reverse on SL'; subsequent reversed trade "
                 "carries its own SL/TP.",
        verifier=_v_s09))

    # ═══════════════════════════════════════════════════════════════════
    # S10 — on_sl_action="re_execute" with max_re_executions=3
    # After SL closes the trade, the slot re-enters on the next signal up
    # to 3 times. Exit count should exceed entry-signal count.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S10_re_execute", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.10,
              on_sl_action="re_execute", max_re_executions=3)])

    def _v_s10(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_stop_loss", "Stop Loss" in ec,
             f"re_execute still goes through SL exit; got {sorted(ec.keys())}"),
        ]

    out.append(run_test("S10", "on_sl_action='re_execute' max=3 — re-enters after SL",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.10,
                "on_sl_action": "re_execute", "max_re_executions": 3},
        portfolio_dict=pf,
        expected="Stop Loss exits present; slot re-enters up to 3× per signal trigger.",
        verifier=_v_s10))

    # ═══════════════════════════════════════════════════════════════════
    # S11 — on_target_action="reverse"
    # On TP, flip the side. EXIT REASON should contain 'Reverse on TP'.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S11_reverse_on_tp", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.50,
              target_type="percentage", target_value=0.10,
              on_target_action="reverse")])

    def _v_s11(s):
        ec = s["exit_reason_counts"]
        ft = s["fills_tag_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("engine_emits_reverse_on_tp", ft.get("Reverse on TP", 0) > 0,
             f"fills_report.tags must contain 'Reverse on TP'; got {ft}"),
            ("orderbook_propagates_reverse_on_tp", "Reverse on TP" in ec,
             f"orderbook EXIT REASON should also contain 'Reverse on TP'; "
             f"got {sorted(ec.keys())} — close+open same-ts collision masks tag"),
        ]

    out.append(run_test("S11", "on_target_action='reverse' — TP flips position",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.50,
                "target_type": "percentage", "target_value": 0.10,
                "on_target_action": "reverse"},
        portfolio_dict=pf,
        expected="EXIT REASON includes 'Reverse on TP'; reversed leg has fresh SL/TP.",
        verifier=_v_s11))

    # ═══════════════════════════════════════════════════════════════════
    # S12 — sl_wait_bars: require 3 confirmation bars before honoring SL
    # SL price is hit but action waits sl_wait_bars=3. If price recovers
    # before 3 bars elapse, SL is cancelled. Should produce fewer SL exits
    # than S02 (same SL pct without wait).
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S12_sl_wait_bars", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.10,
              sl_wait_bars=3)])

    def _v_s12(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("engine_completed", s["engine_trades"] >= 0,
             "engine completed without crash"),
        ]

    out.append(run_test("S12", "sl_wait_bars=3 — SL needs 3 confirmation bars",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.10,
                "sl_wait_bars": 3},
        portfolio_dict=pf,
        expected="Fewer SL exits than no-wait baseline because brief breaches "
                 "are filtered.",
        verifier=_v_s12))

    # ═══════════════════════════════════════════════════════════════════
    # S13 — Tighter target lock (trigger 0.05% / minimum 0.02%)
    # Target lock should fire on most modestly-profitable trades, ratchet
    # SL up to lock_minimum. Subsequent dips trigger 'Trailing SL' exits.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S13_tight_lock", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.40,
              target_lock_trigger=0.05, target_lock_minimum=0.02)])

    def _v_s13(s):
        ec = s["exit_reason_counts"]
        sl_total = ec.get("Stop Loss", 0) + ec.get("Trailing SL", 0)
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_sl_exits", sl_total > 0,
             f"need SL exits; counts={ec}"),
        ]

    out.append(run_test("S13", "Tight target lock: trigger 0.05%, minimum 0.02%",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.40,
                "target_lock_trigger": 0.05, "target_lock_minimum": 0.02},
        portfolio_dict=pf,
        expected="Most trades touch lock trigger; later SL hits tagged Trailing SL.",
        verifier=_v_s13))

    # ═══════════════════════════════════════════════════════════════════
    # S14 — Multi-slot mixed SL types in one portfolio
    # 4 slots, each with a different stop_loss_type. Verifies that the
    # engine isolates per-slot SL config (no cross-leakage).
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S14_mixed_sl_types", slots=[
        _slot("none_sl",   strategy="EMA Cross"),
        _slot("pct_sl",    strategy="EMA Cross",
              stop_loss_type="percentage", stop_loss_value=0.10),
        _slot("pts_sl",    strategy="EMA Cross",
              bar_type="GBPUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
              stop_loss_type="points", stop_loss_value=0.0010),
        _slot("trail_sl",  strategy="EMA Cross",
              bar_type="USDJPY.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
              stop_loss_type="trailing", stop_loss_value=0.30,
              trailing_sl_step=0.05, trailing_sl_offset=0.02),
    ])

    def _v_s14(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_sl_exits", ("Stop Loss" in ec or "Trailing SL" in ec),
             f"4 slots, 3 with SL; counts={ec}"),
            ("multi_slot",     s["orderbook_trades"] > 5,
             f"4 slots over 5 days should produce >5 trades; got {s['orderbook_trades']}"),
        ]

    out.append(run_test("S14", "Multi-slot mixed SL types (none/pct/pts/trailing)",
        params={"slot_count": 4,
                "sl_types": ["none", "percentage 0.10", "points 0.0010",
                             "trailing 0.30/0.05/0.02"]},
        portfolio_dict=pf,
        expected="All 4 slots run; each isolates its own SL config.",
        verifier=_v_s14))

    # ═══════════════════════════════════════════════════════════════════
    # S15 — Compound: tight pct SL + reverse + max_re_executions=5
    # Aggressive scenario — reversal leg can itself reverse on SL up to 5×.
    # Should produce many 'Reverse on SL' exits.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S15_compound_reverse", slots=[
        _slot("a", stop_loss_type="percentage", stop_loss_value=0.05,
              on_sl_action="reverse", max_re_executions=5,
              target_type="percentage", target_value=0.20)])

    def _v_s15(s):
        ec = s["exit_reason_counts"]
        ft = s["fills_tag_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("engine_emits_reverse_on_sl", ft.get("Reverse on SL", 0) > 0,
             f"compound reverse must emit 'Reverse on SL' in fills.tags; got {ft}"),
            ("orderbook_propagates_reverse_on_sl", "Reverse on SL" in ec,
             f"orderbook should show 'Reverse on SL'; got {sorted(ec.keys())} — "
             f"close+open same-ts masks the close tag in the report builder"),
        ]

    out.append(run_test("S15", "Compound: tight SL 0.05% + reverse + max_re=5",
        params={"stop_loss_type": "percentage", "stop_loss_value": 0.05,
                "on_sl_action": "reverse", "max_re_executions": 5,
                "target_type": "percentage", "target_value": 0.20},
        portfolio_dict=pf,
        expected="Many Reverse on SL exits; reversal chain limited by max_re.",
        verifier=_v_s15))

    # ═══════════════════════════════════════════════════════════════════
    # S16 — All-stoploss-features-enabled (most complex)
    # Three slots covering trailing+lock, points+TP+reverse,
    # percentage+TP+re_execute. End-to-end exercise of every SL surface.
    # ═══════════════════════════════════════════════════════════════════
    pf = _portfolio("S16_all_features", slots=[
        _slot("trail_lock",
              stop_loss_type="trailing", stop_loss_value=0.25,
              trailing_sl_step=0.05, trailing_sl_offset=0.02,
              target_lock_trigger=0.10, target_lock_minimum=0.05,
              target_type="percentage", target_value=0.50),
        _slot("pts_reverse",
              bar_type="GBPUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
              stop_loss_type="points", stop_loss_value=0.0008,
              target_type="points", target_value=0.0020,
              on_sl_action="reverse"),
        _slot("pct_reexec",
              bar_type="USDJPY.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
              stop_loss_type="percentage", stop_loss_value=0.08,
              target_type="percentage", target_value=0.15,
              on_sl_action="re_execute", max_re_executions=2,
              sl_wait_bars=2),
    ])

    def _v_s16(s):
        ec = s["exit_reason_counts"]
        return [
            ("trades_executed", s["orderbook_trades"] > 0, f"{s['orderbook_trades']} trades"),
            ("has_diversity", len(ec) >= 2,
             f"need ≥2 distinct exit reasons across 3 slots; got {ec}"),
            ("has_sl_or_tp",
             any(k in ec for k in ("Stop Loss", "Trailing SL", "Take Profit",
                                    "Reverse on SL", "Reverse on TP")),
             f"need at least one SL/TP class exit; got {sorted(ec.keys())}"),
        ]

    out.append(run_test("S16", "All-features: trailing+lock + points+reverse + pct+re_execute",
        params={"slot_count": 3, "features":
                ["trailing+lock+TP", "points+TP+reverse", "pct+TP+re_execute+wait"]},
        portfolio_dict=pf,
        expected="Diverse EXIT REASONs across slots; engine handles all "
                 "SL features simultaneously.",
        verifier=_v_s16))

    # ─────────────────────────────────────────────────────────────────
    # Persist
    # ─────────────────────────────────────────────────────────────────
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nWrote {len(out)} test results -> {RESULTS_PATH}", flush=True)
    print(f"Per-test portfolios saved under {PORTFOLIOS_DIR}", flush=True)


if __name__ == "__main__":
    main()
