"""Orderbook-only leg-SL formula verifier — §1 + §2 of leg_sl_test_scenarios.

Implements Part B of ``leg_sl_test_scenarios.html``: the engine runs a real
backtest using EMA Cross *only as an entry trigger*, then every leg stop-loss is
verified **purely from the orderbook** — no engine internals are read.

For each closed trade whose ``EXIT REASON == "Stop Loss"`` the verifier:

1. Parses ``EXIT DETAILED REASON`` for the engine's computed SL, the entry it
   logged, the trigger side (``≤`` long / ``≥`` short) and — for atr SLs — the
   ATR used at entry (``[atr@entry=…]``).
2. Recomputes the *expected* SL from the row's ``ENTRY PRICE`` using the
   type formula and snaps it to the instrument tick.
3. Asserts ``expected_sl == engine_sl`` to within half a tick, and that the
   trigger side matches the trade direction.

Coverage (the user's selected scope):
* §1 — percentage / points / none golden fixtures (LS-PCT / LS-PTS / LS-NONE).
* §1 + §2 — atr fixtures and the ATR multiplier sweep (period 14 ×
  mult 1.0 / 1.5 / 2.0 / 3.0), plus a monotonicity check that the mean SL
  distance widens with the multiplier.

Trailing (§3 / §5 TM-01), the asset×timeframe matrix (§5) and MIS/NRML (§4,
blocked on TBD-7) are out of scope for this pass.

Output: ``5. Logics/sl_formula_tests/``
  * ``sl_formula_results.json``  — raw per-scenario summaries
  * ``portfolios/*.json``        — the saved portfolio for each scenario
  * ``sl_formula_report.html``   — generated by the companion report script

Run from the project root::

    python verify_leg_sl_formulas.py
    python tests\\smoke_tests\\verify_leg_sl_formulas_report.py
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
import traceback
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

PROJECT_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(PROJECT_DIR))

from core.backtest_runner import run_portfolio_backtest  # noqa: E402
from core.instrument_factory.catalog_lookup import catalog_instrument  # noqa: E402
from core.models import portfolio_from_dict  # noqa: E402
from core.report_generator import build_orderbook_dataframe  # noqa: E402

CATALOG_PATH = str(PROJECT_DIR / "catalog")
OUT_DIR = PROJECT_DIR / "5. Logics" / "sl_formula_tests"
RESULTS_PATH = OUT_DIR / "sl_formula_results.json"
PORTFOLIOS_DIR = OUT_DIR / "portfolios"

# Baseline instrument / window (matches stress_test_stoploss.py defaults so the
# catalog data is known-present). 1-min EURUSD over 5 days = ~7000 bars.
BAR_TYPE = "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL"
DEFAULT_START = "2024-12-02"
DEFAULT_END = "2024-12-06"

# A fast/slow pair that crosses often → plenty of trades to exercise the SL on.
EMA_PARAMS = {"fast_ema_period": 5, "slow_ema_period": 20}

# Use Path A (in-process BacktestEngine) so orderbook rows are deterministic.
os.environ["_USE_BACKTEST_NODE"] = "0"

# Max per-trade rows persisted to JSON (checks still run over *all* trades).
SAMPLE_CAP = 25


# ─────────────────────────────────────────────────────────────────────
# Portfolio builders (mirrors stress_test_stoploss.py)
# ─────────────────────────────────────────────────────────────────────
def _slot(slot_id: str = "a", **exit_overrides) -> dict:
    ec: dict[str, Any] = {
        "stop_loss_type": "none", "stop_loss_value": 0.0,
        "sl_atr_period": 0, "sl_atr_multiplier": 0.0,
        "target_type": "none", "target_value": 0.0,
        "sl_wait_bars": 0, "sl_wait_sec": 0,
        "on_sl_action": "close", "on_target_action": "close",
    }
    ec.update(exit_overrides)
    return {
        "slot_id": slot_id,
        "strategy_name": "EMA Cross",
        "strategy_params": dict(EMA_PARAMS),
        "bar_type_str": BAR_TYPE,
        "lots": 0.01,
        "allocation_pct": 0.0,
        "exit_config": ec,
        "enabled": True,
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
    }


def _portfolio(name: str, **exit_overrides) -> dict:
    return {
        "name": name,
        "description": "leg-SL formula verification portfolio",
        "starting_capital": 100_000.0,
        "allocation_mode": "equal",
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
        "slots": [_slot("a", **exit_overrides)],
    }


# ─────────────────────────────────────────────────────────────────────
# Orderbook parsing + expected-SL recomputation
# ─────────────────────────────────────────────────────────────────────
_RE_SL = re.compile(
    r"(?:≤|<=|≥|>=)\s*SL=([\d.]+)\s*\(entry\s+([\d.]+)")
_RE_OP = re.compile(r"price=[\d.]+\s*(≤|<=|≥|>=)\s*SL")
_RE_ATR = re.compile(r"atr@entry=([\d.]+)")


def _parse_sl_reason(detailed: str) -> dict | None:
    """Pull engine SL, logged entry, trigger op and atr@entry from the tag.

    Returns ``None`` if the string isn't a parseable SL reason.
    """
    m = _RE_SL.search(detailed or "")
    if not m:
        return None
    op_m = _RE_OP.search(detailed)
    atr_m = _RE_ATR.search(detailed)
    op = op_m.group(1) if op_m else ""
    return {
        "engine_sl": float(m.group(1)),
        "logged_entry": float(m.group(2)),
        "op": op,
        "is_long": op in ("≤", "<="),
        "atr_at_entry": float(atr_m.group(1)) if atr_m else None,
    }


def _expected_sl(entry: float, is_long: bool, sl_type: str,
                 value: float, mult: float, atr: float | None,
                 tick: float) -> float | None:
    """Recompute the expected SL from the realised fill, then snap to tick."""
    if sl_type == "percentage":
        raw = entry * (1 - value / 100) if is_long else entry * (1 + value / 100)
    elif sl_type == "points":
        raw = entry - value if is_long else entry + value
    elif sl_type == "atr":
        if atr is None:
            return None
        dist = mult * atr
        raw = entry - dist if is_long else entry + dist
    else:
        return None
    if tick > 0:
        return round(raw / tick) * tick
    return raw


def _verify_sl_trades(orderbook, sl_type: str, value: float,
                      mult: float, tick: float) -> dict:
    """Per-row recompute + assert over every Stop Loss exit in the orderbook."""
    passed: list[tuple[str, str]] = []
    failed: list[tuple[str, str]] = []
    sample: list[dict] = []
    distances: list[float] = []
    n_sl = 0
    half_tick = tick * 0.5 + 1e-9

    if orderbook is None or orderbook.empty:
        return {"n_sl_exits": 0, "checks_passed": [], "checks_failed": [],
                "sample": [], "mean_sl_distance": 0.0}

    for _, row in orderbook.iterrows():
        if str(row.get("EXIT REASON", "")).strip() != "Stop Loss":
            continue
        parsed = _parse_sl_reason(str(row.get("EXIT DETAILED REASON", "")))
        if parsed is None:
            failed.append((f"trade #{n_sl}", "could not parse EXIT DETAILED REASON"))
            continue
        n_sl += 1
        entry = float(row.get("ENTRY PRICE", 0.0) or 0.0)
        engine_sl = parsed["engine_sl"]
        is_long = parsed["is_long"]
        exp = _expected_sl(entry, is_long, sl_type, value, mult,
                           parsed["atr_at_entry"], tick)

        ok_formula = exp is not None and abs(exp - engine_sl) <= half_tick
        # Trigger side: long SLs sit below entry, short SLs above.
        ok_side = (is_long and engine_sl < entry) or (not is_long and engine_sl > entry)
        # Entry consistency: orderbook ENTRY PRICE ~ the entry the engine logged.
        ok_entry = abs(entry - parsed["logged_entry"]) <= tick

        label = f"{sl_type} SL #{n_sl} ({'LONG' if is_long else 'SHORT'})"
        detail = (f"entry={entry:g} expected_sl={exp:g} engine_sl={engine_sl:g} "
                  f"diff={abs(exp - engine_sl):.2e}" if exp is not None
                  else f"entry={entry:g} engine_sl={engine_sl:g} (no expected)")
        (passed if (ok_formula and ok_side and ok_entry) else failed).append(
            (label, detail + ("" if ok_side else " | SIDE WRONG")
             + ("" if ok_entry else " | ENTRY MISMATCH")))

        distances.append(abs(entry - engine_sl))
        if len(sample) < SAMPLE_CAP:
            sample.append({
                "direction": "LONG" if is_long else "SHORT",
                "entry": round(entry, 6),
                "expected_sl": round(exp, 6) if exp is not None else None,
                "engine_sl": round(engine_sl, 6),
                "atr_at_entry": parsed["atr_at_entry"],
                "ok": bool(ok_formula and ok_side and ok_entry),
            })

    mean_dist = (sum(distances) / len(distances)) if distances else 0.0
    return {
        "n_sl_exits": n_sl,
        "checks_passed": [{"label": l, "detail": d} for l, d in passed],
        "checks_failed": [{"label": l, "detail": d} for l, d in failed],
        "sample": sample,
        "mean_sl_distance": round(mean_dist, 8),
    }


# ─────────────────────────────────────────────────────────────────────
# Scenario runner
# ─────────────────────────────────────────────────────────────────────
def run_scenario(test_id: str, name: str, sl_type: str, value: float,
                 mult: float, exit_cfg: dict, tick: float,
                 expected: str, expect_sl_exits: bool = True) -> dict:
    print(f"[{test_id}] {name}", flush=True)
    t0 = time.time()
    PORTFOLIOS_DIR.mkdir(parents=True, exist_ok=True)
    pf_dict = _portfolio(f"{test_id}_{sl_type}", **exit_cfg)
    (PORTFOLIOS_DIR / f"{test_id}.json").write_text(
        json.dumps(pf_dict, indent=2, default=str), encoding="utf-8")

    try:
        pf = portfolio_from_dict(pf_dict)
        results = run_portfolio_backtest(catalog_path=CATALOG_PATH, portfolio=pf)
        orderbook = build_orderbook_dataframe({pf_dict["name"]: results})
        n_trades = int(len(orderbook)) if orderbook is not None else 0

        v = _verify_sl_trades(orderbook, sl_type, value, mult, tick)
        checks_passed = list(v["checks_passed"])
        checks_failed = list(v["checks_failed"])

        if expect_sl_exits:
            ok = v["n_sl_exits"] > 0
            (checks_passed if ok else checks_failed).append(
                {"label": "produced_sl_exits",
                 "detail": f"{v['n_sl_exits']} Stop Loss exits"})
        else:
            ok = v["n_sl_exits"] == 0
            (checks_passed if ok else checks_failed).append(
                {"label": "no_sl_exits",
                 "detail": f"{v['n_sl_exits']} Stop Loss exits (want 0)"})

        status = "ok" if not checks_failed else "fail"
        elapsed = time.time() - t0
        print(f"   -> {status.upper()}  trades={n_trades}  sl_exits={v['n_sl_exits']}  "
              f"checks={len(checks_passed)}/{len(checks_passed) + len(checks_failed)}  "
              f"({elapsed:.1f}s)", flush=True)
        return {
            "test_id": test_id, "name": name, "status": status,
            "params": {"stop_loss_type": sl_type, "stop_loss_value": value,
                       "sl_atr_multiplier": mult, **exit_cfg},
            "expected": expected, "tick": tick,
            "orderbook_trades": n_trades, "n_sl_exits": v["n_sl_exits"],
            "mean_sl_distance": v["mean_sl_distance"],
            "sample": v["sample"],
            "checks_passed": checks_passed, "checks_failed": checks_failed,
            "verification_count": f"{len(checks_passed)}/"
                                  f"{len(checks_passed) + len(checks_failed)}",
            "elapsed_sec": round(elapsed, 1),
        }
    except Exception as e:
        elapsed = time.time() - t0
        print(f"   -> ERROR  {e!r}  ({elapsed:.1f}s)", flush=True)
        return {
            "test_id": test_id, "name": name, "status": "error",
            "params": {"stop_loss_type": sl_type, **exit_cfg},
            "expected": expected, "error": repr(e),
            "traceback": traceback.format_exc(limit=5),
            "elapsed_sec": round(elapsed, 1),
        }


def main() -> None:
    inst = catalog_instrument(BAR_TYPE)
    if inst is None:
        print(f"FATAL: instrument for {BAR_TYPE} not found in {CATALOG_PATH}.",
              flush=True)
        sys.exit(2)
    tick = float(inst.price_increment)
    print(f"Instrument {inst.id}  tick={tick}  precision={inst.price_precision}\n",
          flush=True)

    out: list[dict] = []

    # §1 — percentage (LS-PCT). 0.05% / 0.10% on EURUSD ≈ 5 / 10 pips → SL exits.
    for tid, v in [("PCT-05", 0.05), ("PCT-10", 0.10)]:
        out.append(run_scenario(
            tid, f"Percentage SL {v}% — expected = entry × (1∓{v}/100), tick-snapped",
            "percentage", v, 0.0,
            {"stop_loss_type": "percentage", "stop_loss_value": v}, tick,
            expected=f"Every Stop Loss exit's engine SL equals snap(entry×(1∓{v}/100))."))

    # §1 — points (LS-PTS). 5 / 10 pip absolute distances.
    for tid, v in [("PTS-0005", 0.0005), ("PTS-0010", 0.0010)]:
        out.append(run_scenario(
            tid, f"Points SL {v} — expected = entry ∓ {v}, tick-snapped",
            "points", v, 0.0,
            {"stop_loss_type": "points", "stop_loss_value": v}, tick,
            expected=f"Every Stop Loss exit's engine SL equals snap(entry∓{v})."))

    # §1 — none (LS-NONE). No SL armed → no Stop Loss exits.
    out.append(run_scenario(
        "NONE", "No SL — leg never stopped (negative fixture)",
        "none", 0.0, 0.0, {"stop_loss_type": "none"}, tick,
        expected="No 'Stop Loss' exits appear in the orderbook.",
        expect_sl_exits=False))

    # §1 + §2 — ATR sweep (LS-ATR + multiplier sweep). period 14 × mult ladder.
    atr_results: list[dict] = []
    for tid, mult in [("ATR-10", 1.0), ("ATR-15", 1.5),
                      ("ATR-20", 2.0), ("ATR-30", 3.0)]:
        r = run_scenario(
            tid, f"ATR SL period 14 × {mult} — expected = entry ∓ {mult}×ATR, tick-snapped",
            "atr", 0.0, mult,
            {"stop_loss_type": "atr", "sl_atr_period": 14, "sl_atr_multiplier": mult},
            tick,
            expected=f"Every Stop Loss exit's engine SL equals "
                     f"snap(entry ∓ {mult}×ATR@entry).")
        out.append(r)
        atr_results.append(r)

    # §2 — monotonicity: mean SL distance must widen as the multiplier rises.
    dists = [(r["params"].get("sl_atr_multiplier", 0.0),
              r.get("mean_sl_distance", 0.0))
             for r in atr_results if r.get("status") != "error"
             and r.get("n_sl_exits", 0) > 0]
    dists.sort(key=lambda x: x[0])
    mono_passed, mono_failed = [], []
    monotone = all(dists[i][1] <= dists[i + 1][1] + 1e-12
                   for i in range(len(dists) - 1)) and len(dists) >= 2
    detail = "; ".join(f"mult {m}→dist {d:.6f}" for m, d in dists) or "no atr SL exits"
    (mono_passed if monotone else mono_failed).append(
        {"label": "mean_sl_distance_increases_with_multiplier", "detail": detail})
    out.append({
        "test_id": "ATR-SWEEP", "name": "ATR multiplier sweep — distance monotonicity",
        "status": "ok" if monotone else "fail",
        "params": {"multipliers": [m for m, _ in dists]},
        "expected": "Mean SL distance grows monotonically with the ATR multiplier.",
        "orderbook_trades": 0, "n_sl_exits": sum(r.get("n_sl_exits", 0) for r in atr_results),
        "sample": [], "checks_passed": mono_passed, "checks_failed": mono_failed,
        "verification_count": f"{len(mono_passed)}/{len(mono_passed) + len(mono_failed)}",
        "elapsed_sec": 0.0,
    })

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_PATH.write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")

    n_pass = sum(1 for r in out if r["status"] == "ok")
    n_fail = sum(1 for r in out if r["status"] == "fail")
    n_err = sum(1 for r in out if r["status"] == "error")
    print(f"\n{'='*60}")
    print(f"  {n_pass} pass / {n_fail} fail / {n_err} error  (of {len(out)})")
    print(f"  results -> {RESULTS_PATH}")
    print(f"{'='*60}")
    sys.exit(0 if (n_fail == 0 and n_err == 0) else 1)


if __name__ == "__main__":
    main()
