"""Aggressive stress tests on portfolio backtests x multi-user identity.

25 tests covering:
- Multiplier extremes (tiny/huge/zero/runaway) with cap interaction
- Custom-built portfolios with deliberately-tricky configurations
- Existing portfolios under restrictive user constraints
- Complex setting combinations (RBO + pf_sl + pf_tgt + trailing + move_sl)
- Edge cases that should fail loudly (empty slots, mismatched allowlist,
  conflicting timing windows, all-disabled slots, wrong allocation totals)
- API-level concurrency / round-trip stress

Each test uses one of: a baseline portfolio loaded from disk and mutated
in-place, OR a freshly-constructed portfolio dict built from scratch
(the "custom" variants — these prove the backend handles minimal /
non-standard configs as well as the full FX_9_Slot baseline).

Output goes to ``5. Logics/stress_tests/`` per the request:
- stress_test_results.json -- raw per-test summaries
- stress_test_report.html  -- generated by stress_test_portfolios_report.py

Run from the project root:  python stress_test_portfolios.py
"""

from __future__ import annotations

import copy
import json
import os
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

PROJECT_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(PROJECT_DIR))

from core.backtest_runner import run_portfolio_backtest  # noqa: E402
from core.models import portfolio_from_dict  # noqa: E402
from core.users import save_users, load_users  # noqa: E402

CATALOG_PATH = str(PROJECT_DIR / "catalog")
BASELINE_PATH = PROJECT_DIR / "portfolios" / "_default" / "FX_9_Slot_2015_2024.json"
OUT_DIR = PROJECT_DIR / "5. Logics" / "stress_tests"
RESULTS_PATH = OUT_DIR / "stress_test_results.json"

DEFAULT_START = "2024-12-02"
DEFAULT_END = "2024-12-06"

# Test users registry — covers extremes plus realistic tiers.
TEST_REGISTRY = {
    "users": [
        {"user_id": "_default",     "alias": "Default",            "multiplier": 1.0,
         "allowed_instruments": None},
        {"user_id": "alice",        "alias": "Alice (FX)",         "multiplier": 2.0,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "bob",          "alias": "Bob (Crypto-only)",  "multiplier": 0.5,
         "allowed_instruments": ["BTCUSD"]},
        {"user_id": "trader_safe",  "alias": "Junior",             "multiplier": 0.01,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "trader_agg",   "alias": "Senior",             "multiplier": 3.0,
         "allowed_instruments": None},
        {"user_id": "runaway",      "alias": "Runaway-Multiplier", "multiplier": 100000.0,
         "allowed_instruments": ["EURUSD", "GBPUSD", "USDJPY"]},
        {"user_id": "alice_only",   "alias": "Alice EURUSD-only",  "multiplier": 1.5,
         "allowed_instruments": ["EURUSD"]},
        {"user_id": "noaccess",     "alias": "Empty allowlist",    "multiplier": 1.0,
         "allowed_instruments": []},
        {"user_id": "case_test",    "alias": "Lowercase allowlist","multiplier": 1.0,
         "allowed_instruments": ["eurusd"]},
    ]
}


# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────
def _load_baseline_dict(start: str = DEFAULT_START, end: str = DEFAULT_END) -> dict:
    with open(BASELINE_PATH) as f:
        d = json.load(f)
    d["start_date"] = start
    d["end_date"] = end
    for slot in d.get("slots", []):
        slot["start_date"] = start
        slot["end_date"] = end
    return d


def _build_minimal_portfolio(name: str, slots: list[dict], **portfolio_overrides) -> dict:
    """Construct a portfolio dict from scratch with only the fields needed."""
    pf = {
        "name": name,
        "description": "stress-test portfolio (synthetic)",
        "starting_capital": 100_000.0,
        "allocation_mode": "equal",
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
        "slots": slots,
    }
    pf.update(portfolio_overrides)
    return pf


def _slot(slot_id: str, bar_type: str, lots: float = 0.01,
          strategy: str = "EMA Cross", **overrides) -> dict:
    s = {
        "slot_id": slot_id,
        "strategy_name": strategy,
        "strategy_params": {},
        "bar_type_str": bar_type,
        "lots": lots,
        "allocation_pct": 0.0,
        "exit_config": {
            "stop_loss_type": "none", "stop_loss_value": 0.0,
            "trailing_sl_step": 0.0, "trailing_sl_offset": 0.0,
            "target_type": "none", "target_value": 0.0,
            "sl_wait_bars": 0, "on_sl_action": "close",
            "on_target_action": "close", "max_re_executions": 0,
            "squareoff_time": None, "squareoff_tz": None,
        },
        "enabled": True,
        "start_date": DEFAULT_START,
        "end_date": DEFAULT_END,
    }
    s.update(overrides)
    return s


def _avg_qty(fills_report) -> float | None:
    if fills_report is None:
        return None
    try:
        if hasattr(fills_report, "empty") and fills_report.empty:
            return None
        for col in ("quantity", "last_qty", "size"):
            if hasattr(fills_report, "columns") and col in fills_report.columns:
                vals = [float(v) for v in fills_report[col] if v is not None]
                return round(sum(vals) / len(vals), 4) if vals else None
    except Exception:
        return None
    return None


def _summarise(results: dict) -> dict:
    per_strategy = results.get("per_strategy", {}) or {}
    return {
        "total_pnl":     round(float(results.get("total_pnl", 0.0) or 0.0), 4),
        "total_trades":  int(results.get("total_trades", 0) or 0),
        "wins":          int(results.get("wins", 0) or 0),
        "losses":        int(results.get("losses", 0) or 0),
        "slot_count":    len(per_strategy),
        "avg_fill_qty":  _avg_qty(results.get("fills_report")),
        "pf_clip_reason": results.get("pf_clip_reason"),
    }


def run_backtest_test(test_id: str, name: str, params: dict,
                      portfolio_dict: dict, expected: str,
                      user_id: str | None,
                      should_error: bool = False,
                      expected_error_substring: str | None = None) -> dict:
    """Generic backtest runner. Captures errors so we can verify negative
    paths fire correctly (e.g. all-disabled-slots should ValueError).
    """
    print(f"[{test_id}] {name}  user={user_id}", flush=True)
    t0 = time.time()
    try:
        pf = portfolio_from_dict(portfolio_dict)
        results = run_portfolio_backtest(catalog_path=CATALOG_PATH,
                                         portfolio=pf,
                                         user_id=user_id)
        elapsed = time.time() - t0
        if should_error:
            return {"test_id": test_id, "name": name, "params": params,
                    "expected": expected, "user_id": user_id,
                    "status": "fail",
                    "error": f"Expected error but ran successfully: {_summarise(results)}",
                    "elapsed_sec": round(elapsed, 1), "kind": "backtest"}
        summary = _summarise(results)
        summary.update({"test_id": test_id, "name": name, "params": params,
                        "expected": expected, "user_id": user_id,
                        "elapsed_sec": round(elapsed, 1), "status": "ok",
                        "kind": "backtest"})
        clip = f"  CLIP={summary['pf_clip_reason']}" if summary.get("pf_clip_reason") else ""
        print(f"   -> ok  pnl=${summary['total_pnl']:.2f}  "
              f"trades={summary['total_trades']}  "
              f"avg_qty={summary['avg_fill_qty']}  "
              f"({summary['elapsed_sec']}s){clip}", flush=True)
        return summary
    except Exception as e:
        elapsed = time.time() - t0
        err_str = repr(e)
        if should_error:
            matched = (expected_error_substring is None or
                       expected_error_substring.lower() in err_str.lower())
            verdict = "ok" if matched else "fail"
            print(f"   -> {verdict} (expected error)  err={e!r}  ({elapsed:.1f}s)",
                  flush=True)
            return {"test_id": test_id, "name": name, "params": params,
                    "expected": expected, "user_id": user_id,
                    "status": verdict, "expected_error_substring": expected_error_substring,
                    "error": err_str, "elapsed_sec": round(elapsed, 1),
                    "kind": "backtest_negative"}
        tb = traceback.format_exc(limit=5)
        print(f"   -> ERROR  {e!r}  ({elapsed:.1f}s)", flush=True)
        return {"test_id": test_id, "name": name, "params": params,
                "expected": expected, "user_id": user_id,
                "status": "error", "error": err_str, "traceback": tb,
                "elapsed_sec": round(elapsed, 1), "kind": "backtest"}


def run_api_test(test_id: str, name: str, expected: str, fn) -> dict:
    print(f"[{test_id}] {name}  (api)", flush=True)
    t0 = time.time()
    try:
        import server
        client = server.app.test_client()
        result = fn(client)
        elapsed = time.time() - t0
        verdict = "ok" if result.get("pass") else "fail"
        print(f"   -> {verdict}: {result.get('detail','')}  ({elapsed:.1f}s)", flush=True)
        return {"test_id": test_id, "name": name, "expected": expected,
                "status": verdict, "detail": result.get("detail", ""),
                "elapsed_sec": round(elapsed, 1), "kind": "api",
                "observations": result.get("observations", {})}
    except Exception as e:
        elapsed = time.time() - t0
        tb = traceback.format_exc(limit=5)
        print(f"   -> ERROR: {e!r}", flush=True)
        return {"test_id": test_id, "name": name, "expected": expected,
                "status": "error", "error": repr(e), "traceback": tb,
                "elapsed_sec": round(elapsed, 1), "kind": "api"}


# ─────────────────────────────────────────────────────────────────────
# 25 tests
# ─────────────────────────────────────────────────────────────────────
def _full_complex_bundle(d):
    """Apply most aggressive setting combination: RBO + window + sqoff +
    pf_sl trailing + pf_tgt trailing + move_sl + reverse-on-SL."""
    d["rbo_enabled"] = True
    d["range_monitoring_start"] = "09:00:00"
    d["range_monitoring_end"]   = "10:00:00"
    d["rbo_entry_start"] = "10:00:00"
    d["rbo_entry_end"]   = "15:00:00"
    d["rbo_entry_at"]    = "Any"
    d["rbo_cancel_other_side"] = True
    d["entry_start_time"] = "10:00:00"
    d["entry_end_time"]   = "15:00:00"
    d["squareoff_time"] = "15:30"
    d["squareoff_tz"]   = "UTC"
    d["delay_between_legs_sec"] = 60
    d["pf_sl_enabled"]       = True
    d["pf_sl_value"]         = 80.0
    d["pf_sl_trail_enabled"] = True
    d["pf_sl_trail_every"]   = 20.0
    d["pf_sl_trail_by"]      = 10.0
    d["pf_tgt_enabled"]      = True
    d["pf_tgt_value"]        = 50.0
    d["pf_tgt_trail_enabled"] = True
    d["pf_tgt_trail_when_profit_reach"] = 30.0
    d["pf_tgt_trail_every"]  = 10.0
    d["pf_tgt_trail_by"]     = 5.0
    d["move_sl_enabled"]     = True
    d["move_sl_safety_sec"]  = 300
    d["move_sl_trail_after"] = True


def main():
    os.environ["_USE_BACKTEST_NODE"] = "1"
    saved_registry = load_users()
    save_users(TEST_REGISTRY)

    out: list[dict] = []

    # ── S01: Full complex bundle, _default (baseline) ──────────────────
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "S01", "Full complex bundle (RBO + trailing pf_sl + trailing pf_tgt + move_sl) — _default baseline",
        params={"complex": "RBO + window + sqoff + pf_sl 80 trail 20/10 + pf_tgt 50 trail 30/10/5 + move_sl 300s trail_after",
                "user": "_default", "multiplier": 1.0},
        portfolio_dict=pf,
        expected="Engine handles all toggles together; baseline qty for ratio comparisons",
        user_id="_default",
    ))
    baseline_qty = out[-1].get("avg_fill_qty")

    # ── S02: Same bundle, runaway × 100k → cap binds ───────────────────
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "S02", "Full bundle + runaway ×100,000 — admin cap MUST clamp",
        params={"user": "runaway", "multiplier": 100000.0,
                "expected_qty": "10,000,000 (FX cap)"},
        portfolio_dict=pf,
        expected="avg_fill_qty == 10M regardless of multiplier; PnL inflates but engine survives",
        user_id="runaway",
    ))

    # ── S03: Same bundle, trader_safe × 0.01 → tiny PnL ────────────────
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "S03", "Full bundle + trader_safe ×0.01 — tiny exposure, trailing pf_sl rarely fires",
        params={"user": "trader_safe", "multiplier": 0.01},
        portfolio_dict=pf,
        expected="avg_fill_qty ~ 1% baseline; cumulative PnL tiny so trailing pf_sl unlikely to bind",
        user_id="trader_safe",
    ))

    # ── S04: Custom 1-slot EURUSD with reverse-on-SL ───────────────────
    pf = _build_minimal_portfolio(
        "Custom_1slot_reverse",
        slots=[_slot("eu_only", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
                     exit_config={
                         "stop_loss_type": "percentage", "stop_loss_value": 0.1,
                         "trailing_sl_step": 0, "trailing_sl_offset": 0,
                         "target_type": "percentage", "target_value": 0.2,
                         "sl_wait_bars": 0, "on_sl_action": "reverse",
                         "on_target_action": "close", "max_re_executions": 5,
                         "squareoff_time": None, "squareoff_tz": None,
                     })])
    out.append(run_backtest_test(
        "S04", "Custom 1-slot EURUSD with reverse-on-SL + 5 max re-executions",
        params={"slots": 1, "exit": "SL 0.1% reverse, TP 0.2% close, max_re=5"},
        portfolio_dict=pf,
        expected="Each SL hit flips the position; tracks fills both directions; max_re caps reverses",
        user_id="alice",
    ))

    # ── S05: Custom 9-strategy maxed-out portfolio ─────────────────────
    strategies = ["EMA Cross", "RSI Mean Reversion", "Bollinger Bands", "4 Moving Averages"]
    pf_slots = []
    for i, sym in enumerate(["EURUSD", "GBPUSD", "USDJPY"]):
        for j, strat in enumerate(strategies[:3]):
            pf_slots.append(_slot(f"s{i}{j}", f"{sym}.FOREX_MS-1-MINUTE-MID-EXTERNAL",
                                  lots=0.01, strategy=strat))
    pf = _build_minimal_portfolio("Custom_9strat", slots=pf_slots)
    out.append(run_backtest_test(
        "S05", "Custom 3 symbols × 3 strategies (EMA / RSI / Bollinger) — alice ×2.0",
        params={"slots": 9, "user": "alice", "multiplier": 2.0},
        portfolio_dict=pf,
        expected="All 9 slots run; avg_fill_qty == 2 × matched-strategy baseline",
        user_id="alice",
    ))

    # ── S06: Custom portfolio with all slots disabled ──────────────────
    pf = _build_minimal_portfolio(
        "Custom_alldisabled",
        slots=[_slot("d1", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", enabled=False),
               _slot("d2", "GBPUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", enabled=False)])
    out.append(run_backtest_test(
        "S06", "Custom portfolio: ALL slots disabled — must raise 'No enabled slots'",
        params={"slots": 2, "all_disabled": True},
        portfolio_dict=pf,
        expected="ValueError: No enabled strategy slots in portfolio",
        user_id="_default",
        should_error=True,
        expected_error_substring="no enabled",
    ))

    # ── S07: Custom portfolio with empty slots list ────────────────────
    pf = _build_minimal_portfolio("Custom_empty", slots=[])
    out.append(run_backtest_test(
        "S07", "Custom portfolio: 0 slots — must raise",
        params={"slots": 0},
        portfolio_dict=pf,
        expected="ValueError on empty enabled_slots",
        user_id="_default",
        should_error=True,
        expected_error_substring="no enabled",
    ))

    # ── S08: Custom portfolio with conflicting timing (squareoff < window_end)
    pf = _build_minimal_portfolio(
        "Custom_timing_conflict",
        slots=[_slot("eu", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)],
        entry_start_time="14:00:00", entry_end_time="16:00:00",
        squareoff_time="13:00", squareoff_tz="UTC")
    out.append(run_backtest_test(
        "S08", "Custom: squareoff (13:00) BEFORE entry_start (14:00) — engine should still complete",
        params={"entry_window": "14:00-16:00", "squareoff": "13:00 UTC"},
        portfolio_dict=pf,
        expected="No trades fire (squareoff blocks all entries before window opens); 0 trades",
        user_id="_default",
    ))

    # ── S09: Custom portfolio with empty allowlist user → save 403 ────
    def _s09(client):
        pf = _build_minimal_portfolio("S09",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
        r = client.post("/api/portfolios/save", json=pf,
                        headers={"X-User-Id": "noaccess"})
        return {"pass": r.status_code == 403,
                "detail": f"noaccess (allowlist=[]) save -> {r.status_code}",
                "observations": {"status": r.status_code,
                                 "error": (r.json or {}).get("error")}}
    out.append(run_api_test(
        "S09", "Empty allowlist [] blocks any symbol on save",
        expected="HTTP 403 — empty list means no instruments allowed",
        fn=_s09,
    ))

    # ── S10: Mixed-case allowlist normalization ────────────────────────
    def _s10(client):
        pf = _build_minimal_portfolio("S10",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
        r = client.post("/api/portfolios/save", json=pf,
                        headers={"X-User-Id": "case_test"})
        # allowlist is ["eurusd"], symbol is EURUSD — should match case-insensitively
        ok = r.status_code == 200
        if ok:
            client.post("/api/portfolios/delete", json={"name": "S10"},
                        headers={"X-User-Id": "case_test"})
        return {"pass": ok,
                "detail": f"case_test (allowlist=['eurusd']) saves EURUSD -> {r.status_code}",
                "observations": {"status": r.status_code,
                                 "msg": (r.json or {}).get("message"),
                                 "error": (r.json or {}).get("error")}}
    out.append(run_api_test(
        "S10", "Allowlist case-insensitive matching: ['eurusd'] vs symbol EURUSD",
        expected="HTTP 200 — server uppercases both sides before comparison",
        fn=_s10,
    ))

    # ── S11: Multi-symbol portfolio with partial allowlist match → 403
    def _s11(client):
        pf = _build_minimal_portfolio("S11", slots=[
            _slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL"),
            _slot("b", "BTCUSD.BINANCE_MS-1-DAY-LAST-EXTERNAL"),
        ])
        r = client.post("/api/portfolios/save", json=pf,
                        headers={"X-User-Id": "alice_only"})
        return {"pass": r.status_code == 403,
                "detail": f"alice_only (allowlist=[EURUSD]) saves EURUSD+BTCUSD -> {r.status_code}",
                "observations": {"status": r.status_code,
                                 "error": (r.json or {}).get("error")}}
    out.append(run_api_test(
        "S11", "Save fails on FIRST out-of-allowlist slot in multi-slot portfolio",
        expected="HTTP 403 with descriptive 'BTCUSD not in allowlist' message",
        fn=_s11,
    ))

    # ── S12: trader_agg ×3.0 with reverse-on-SL on FX_9_Slot ──────────
    pf = _load_baseline_dict()
    for slot in pf.get("slots", []):
        slot["exit_config"]["stop_loss_type"] = "percentage"
        slot["exit_config"]["stop_loss_value"] = 0.05
        slot["exit_config"]["on_sl_action"]   = "reverse"
        slot["exit_config"]["max_re_executions"] = 3
    out.append(run_backtest_test(
        "S12", "FX_9_Slot + reverse-on-SL + 3 max re-executions, trader_agg ×3.0",
        params={"user": "trader_agg", "multiplier": 3.0,
                "exit": "SL 0.05% reverse + max_re 3"},
        portfolio_dict=pf,
        expected="Reversals double-count toward total_trades; avg_qty == 3 × baseline",
        user_id="trader_agg",
    ))

    # ── S13: Multi-leg range_breakout custom portfolio ─────────────────
    pf = _build_minimal_portfolio(
        "Custom_RBO_multileg",
        slots=[_slot("rb", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01,
                     strategy="Range Breakout",
                     strategy_params={
                         "num_legs": 3,
                         "leg1_lots": 1, "leg2_lots": 2, "leg3_lots": 3,
                         "range_start_hhmm": 930, "range_end_hhmm": 1030,
                         "breakout_end_hhmm": 1500, "squareoff_hhmm": 1530,
                         "target_pct": 5.0, "stop_pct": 10.0,
                     })])
    out.append(run_backtest_test(
        "S13", "Custom Range Breakout 3-leg (1,2,3 lots) — alice ×2.0",
        params={"strategy": "Range Breakout", "legs": "1+2+3"},
        portfolio_dict=pf,
        expected="3 distinct fill quantities (1×, 2×, 3× base) all scaled by alice ×2.0",
        user_id="alice",
    ))

    # ── S14: pf_tgt fires before pf_sl (target lower than SL) ─────────
    pf = _load_baseline_dict()
    pf["pf_tgt_enabled"] = True
    pf["pf_tgt_value"] = 5.0       # very tight target
    pf["pf_tgt_action"] = "SqOff"
    pf["pf_sl_enabled"] = True
    pf["pf_sl_value"] = 100.0      # generous SL
    out.append(run_backtest_test(
        "S14", "pf_tgt=$5 + pf_sl=$100 — target should clip first if any profit run-up",
        params={"pf_tgt": 5, "pf_sl": 100},
        portfolio_dict=pf,
        expected="If a profitable trade happens, pf_clip_reason=TARGET (not STOPLOSS)",
        user_id="_default",
    ))

    # ── S15: Squareoff in NY timezone vs UTC bars ──────────────────────
    pf = _load_baseline_dict()
    pf["squareoff_time"] = "10:00"
    pf["squareoff_tz"]   = "America/New_York"  # 15:00 UTC
    out.append(run_backtest_test(
        "S15", "Squareoff 10:00 New_York (= 15:00 UTC) on FX_9_Slot",
        params={"squareoff": "10:00 America/New_York"},
        portfolio_dict=pf,
        expected="No fills past 15:00 UTC each day",
        user_id="alice",
    ))

    # ── S16: Very narrow entry window (10 minutes) ─────────────────────
    pf = _load_baseline_dict()
    pf["entry_start_time"] = "12:00:00"
    pf["entry_end_time"]   = "12:10:00"
    out.append(run_backtest_test(
        "S16", "Very narrow entry window 12:00-12:10 UTC",
        params={"entry_window": "12:00-12:10"},
        portfolio_dict=pf,
        expected="Fills cluster at hour 12 only; significantly fewer trades than baseline",
        user_id="_default",
    ))

    # ── S17: run_on_days = ["Wed"] only ────────────────────────────────
    pf = _load_baseline_dict()
    pf["run_on_days"] = ["Wed"]
    out.append(run_backtest_test(
        "S17", "run_on_days = ['Wed'] only — single weekday filter",
        params={"run_on_days": ["Wed"]},
        portfolio_dict=pf,
        expected="All fills on Wednesday only; weekday histogram shows {Wed: N}",
        user_id="alice",
    ))

    # ── S18: Allocation_mode percentage with custom allocations ────────
    pf = _load_baseline_dict()
    pf["allocation_mode"] = "percentage"
    # 9 slots: 30% + 30% + 10% × 7 = 130% (deliberate over-allocation)
    for i, slot in enumerate(pf.get("slots", [])):
        slot["allocation_pct"] = 30.0 if i < 2 else 10.0
    out.append(run_backtest_test(
        "S18", "Allocation_mode='percentage' with allocations summing to 130% (over)",
        params={"allocation_mode": "percentage", "sum": 130},
        portfolio_dict=pf,
        expected="Engine accepts; capital scales by pct/100 per slot — over-allocation just means leverage",
        user_id="_default",
    ))

    # ── S19: trader_safe + complex bundle on existing FX portfolio ─────
    pf = _load_baseline_dict()
    _full_complex_bundle(pf)
    out.append(run_backtest_test(
        "S19", "Existing FX_9_Slot + full complex bundle, trader_safe ×0.01",
        params={"user": "trader_safe", "multiplier": 0.01,
                "complex": "RBO + trailing pf_sl/pf_tgt + move_sl + reverse"},
        portfolio_dict=pf,
        expected="avg_fill_qty == 1% baseline; many trades fire but PnL stays small",
        user_id="trader_safe",
    ))

    # ── S20: Per-user portfolio CRUD round-trip ────────────────────────
    def _s20(client):
        pf = _build_minimal_portfolio("S20_RT",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
        r1 = client.post("/api/portfolios/save", json=pf,
                         headers={"X-User-Id": "alice"})
        r2 = client.get("/api/portfolios/load?name=S20_RT",
                        headers={"X-User-Id": "alice"})
        loaded = (r2.json or {}).get("portfolio", {})
        loaded_lots = loaded.get("slots", [{}])[0].get("lots")
        r3 = client.post("/api/portfolios/delete", json={"name": "S20_RT"},
                         headers={"X-User-Id": "alice"})
        ok = r1.status_code == 200 and r2.status_code == 200 and loaded_lots == 0.01 and r3.status_code == 200
        return {"pass": ok,
                "detail": f"save={r1.status_code}, load={r2.status_code}, lots_back={loaded_lots}, delete={r3.status_code}",
                "observations": {"loaded_name": loaded.get("name")}}
    out.append(run_api_test(
        "S20", "Per-user portfolio CRUD round-trip (save -> load -> verify -> delete)",
        expected="All three calls 200; loaded portfolio matches saved shape",
        fn=_s20,
    ))

    # ── S21: alice cannot load bob's portfolio ─────────────────────────
    def _s21(client):
        pf = _build_minimal_portfolio("S21_BOB",
            slots=[_slot("a", "BTCUSD.BINANCE_MS-1-DAY-LAST-EXTERNAL", lots=1.0)])
        client.post("/api/portfolios/save", json=pf, headers={"X-User-Id": "bob"})
        r = client.get("/api/portfolios/load?name=S21_BOB",
                       headers={"X-User-Id": "alice"})
        client.post("/api/portfolios/delete", json={"name": "S21_BOB"},
                    headers={"X-User-Id": "bob"})
        return {"pass": r.status_code == 404,
                "detail": f"alice loading bob's S21_BOB -> {r.status_code}",
                "observations": {"status": r.status_code,
                                 "error": (r.json or {}).get("error")}}
    out.append(run_api_test(
        "S21", "Cross-user load isolation: alice can't load bob's portfolio",
        expected="HTTP 404 — alice's portfolios/<alice>/ doesn't have bob's file",
        fn=_s21,
    ))

    # ── S22: Concurrent multi-user backtest of same portfolio ──────────
    def _s22(client):
        pf = _build_minimal_portfolio("S22",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=0.01)])
        # Sequential proxy for concurrent — verify no shared mutable state.
        # Drain each stream's body before starting the next request so Flask's
        # stream_with_context generators close cleanly in the test-client
        # lifecycle (production workers each get their own thread/context).
        r_alice = client.post("/api/portfolios/backtest", json={"portfolio": pf},
                              headers={"X-User-Id": "alice"})
        body_alice = r_alice.get_data(as_text=True)
        r_def   = client.post("/api/portfolios/backtest", json={"portfolio": pf},
                              headers={"X-User-Id": "_default"})
        body_def = r_def.get_data(as_text=True)
        ok = (r_alice.status_code == 200 and r_def.status_code == 200
              and "complete" in body_alice and "complete" in body_def)
        return {"pass": ok,
                "detail": f"alice run -> {r_alice.status_code}, _default run -> {r_def.status_code}",
                "observations": {"alice_status": r_alice.status_code,
                                 "default_status": r_def.status_code,
                                 "alice_lines": len(body_alice.splitlines()),
                                 "default_lines": len(body_def.splitlines())}}
    out.append(run_api_test(
        "S22", "Two users back-to-back run the same custom portfolio — no shared-state bug",
        expected="Both backtests complete cleanly with their own multipliers",
        fn=_s22,
    ))

    # ── S23: Save portfolio with very small lots (1e-6) ────────────────
    def _s23(client):
        pf = _build_minimal_portfolio("S23",
            slots=[_slot("a", "EURUSD.FOREX_MS-1-MINUTE-MID-EXTERNAL", lots=1e-6)])
        r = client.post("/api/portfolios/save", json=pf,
                        headers={"X-User-Id": "alice"})
        if r.status_code == 200:
            client.post("/api/portfolios/delete", json={"name": "S23"},
                        headers={"X-User-Id": "alice"})
        return {"pass": r.status_code == 200,
                "detail": f"save lots=1e-6 -> {r.status_code}",
                "observations": {"status": r.status_code}}
    out.append(run_api_test(
        "S23", "Edge case: lots=1e-6 (six-decimal micro-lot)",
        expected="HTTP 200 — JSON serialization preserves the tiny float",
        fn=_s23,
    ))

    # ── S24: /api/users/me reflects admin-edited multiplier mid-session
    def _s24(client):
        before = client.get("/api/users/me", headers={"X-User-Id": "alice"}).json
        # Edit multiplier directly via the admin path
        new_reg = copy.deepcopy(TEST_REGISTRY)
        for u in new_reg["users"]:
            if u["user_id"] == "alice":
                u["multiplier"] = 7.0
        save_users(new_reg)
        after = client.get("/api/users/me", headers={"X-User-Id": "alice"}).json
        save_users(TEST_REGISTRY)  # restore
        ok = before["multiplier"] == 2.0 and after["multiplier"] == 7.0
        return {"pass": ok,
                "detail": f"alice multiplier before={before['multiplier']}, after admin save={after['multiplier']}",
                "observations": {"before": before, "after": after}}
    out.append(run_api_test(
        "S24", "Admin live-edit picked up immediately by next /api/users/me call",
        expected="No restart needed; users.json read every call",
        fn=_s24,
    ))

    # ── S25: /api/users/list survives broken users.json (graceful fallback)
    def _s25(client):
        users_path = PROJECT_DIR / "config" / "users.json"
        backup = users_path.read_text(encoding="utf-8")
        try:
            users_path.write_text("not valid json {[", encoding="utf-8")
            r = client.get("/api/users/list")
            ok = r.status_code == 200 and isinstance((r.json or {}).get("users"), list)
        finally:
            users_path.write_text(backup, encoding="utf-8")
        return {"pass": ok,
                "detail": f"corrupt users.json -> /api/users/list status={r.status_code}, users={(r.json or {}).get('users')}",
                "observations": {"recovered": ok}}
    out.append(run_api_test(
        "S25", "Resilience: corrupt users.json -> picker endpoint still returns a (fallback) list",
        expected="load_users catches JSONDecodeError and returns _default fallback",
        fn=_s25,
    ))

    # Persist
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nWrote {len(out)} test results -> {RESULTS_PATH}", flush=True)

    # Restore registry
    save_users(saved_registry)
    print(f"Restored original registry ({len(saved_registry.get('users', []))} users)",
          flush=True)


if __name__ == "__main__":
    main()
